# [Lollypop](https://wiki.gnome.org/Apps/Lollypop) is a lightweight modern music
# player designed to work excellently on the GNOME desktop environment.

---

services:
  lollypop:
    image: ghcr.io/linuxserver/lollypop
    container_name: lollypop
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/lollypop${DOCKERCONFIGDIR:-}:/config
    # ports:
      # Lollypop desktop gui.
      # - 3000:3000
      # Lollypop desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - lollypop
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}