# [Znc](http://wiki.znc.in/ZNC) is an IRC network bouncer or BNC. It can detach
# the client from the actual IRC server, and also from selected channels.
# Multiple clients from different locations can connect to a single ZNC account
# simultaneously and therefore appear under the same nickname on IRC.

---

services:
  znc:
    image: ghcr.io/linuxserver/znc
    container_name: znc
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/znc${DOCKERCONFIGDIR:-}:/config
    # ports:
      # # Port ZNC listens on.
      # - 6501:6501
    networks:
      default:
        aliases:
          - znc
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
