# [Lychee](https://lycheeorg.github.io/) is a free photo-management tool, which
# runs on your server or web-space. Installing is a matter of seconds. Upload,
# manage and share photos like from a native application. Lychee comes with
# everything you need and all your photos are stored securely.'

---

services:
  lychee:
    image: ghcr.io/linuxserver/lychee
    container_name: lychee
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - DB_CONNECTION=
      - DB_HOST=
      - DB_PORT=
      - DB_USERNAME=
      - DB_PASSWORD=
      - DB_DATABASE=
      # - APP_NAME=Lychee # optional
      # - APP_URL= # optional
      # - TRUSTED_PROXIES= # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/lychee${DOCKERCONFIGDIR:-}:/config
      # Where lychee will store uploaded images.
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/lychee/pictures:/pictures
    # ports:
      # # http gui
      # - 80:80
    networks:
      default:
        aliases:
          - lychee
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
