# [Ungoogled Chromium](https://github.com/ungoogled-software/ungoogled-chromium)
# is Google Chromium, sans dependency on Google web services.

---

services:
  ungoogled-chromium:
    image: ghcr.io/linuxserver/ungoogled-chromium
    container_name: ungoogled-chromium
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - CHROME_CLI=https://www.linuxserver.io/ # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/ungoogled-chromium${DOCKERCONFIGDIR:-}:/config
    # ports:
      # # Ungoogled Chromium desktop gui.
      # - 3000:3000
      # # HTTPS Ungoogled Chromium desktop gui.
      # - 3001:3001
    networks:
      default:
        aliases:
          - ungoogled-chromium
    shm_size: "1gb"
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
