
# [Minetest](http://www.minetest.net/) (server) is a near-infinite-world block
# sandbox game and a game engine, inspired by InfiniMiner, Minecraft, and the
# like.

---

services:
  minetest:
    image: ghcr.io/linuxserver/minetest
    container_name: minetest
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - CLI_ARGS=--gameid devtest # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/minetest/config/.minetest:/config/.minetest
    # ports:
      # - 30000:30000/udp # Port Minetest listens on (UDP).
    networks:
      default:
        aliases:
          - minetest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true