# [FreeCAD](https://www.freecad.org/) is a general-purpose parametric 3D
# computer-aided design (CAD) modeler and a building information modeling (BIM)
# software application with finite element method (FEM) support.

---

services:
  freecad:
    image: ghcr.io/linuxserver/freecad
    container_name: freecad
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/freecad${DOCKERCONFIGDIR:-}:/config
    # ports:
      # # FreeCAD desktop gui.
      # - 3000:3000
      # # FreeCAD desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - freecad
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: ${NETWORK_EXTERNAL:-false}
