
# [FreeCAD](https://www.freecad.org/) is a general-purpose parametric 3D
# computer-aided design (CAD) modeler and a building information modeling (BIM)
# software application with finite element method (FEM) support.

---

services:
  freecad:
    image: ghcr.io/linuxserver/freecad
    container_name: freecad
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/freecad:/config
    # ports:
      # - 3000:3000 # FreeCAD desktop gui.
      # - 3001:3001 # FreeCAD desktop gui HTTPS.
    networks:
      default:
        aliases:
          - freecad
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true