# [Mariadb](https://mariadb.org/) is one of the most popular database servers.
# Made by the original developers of MySQL.

---

services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - MYSQL_ROOT_PASSWORD=ROOT_ACCESS_PASSWORD
      # - MYSQL_DATABASE=USER_DB_NAME # optional
      # - MYSQL_USER=MYSQL_USER # optional
      # - MYSQL_PASSWORD=DATABASE_PASSWORD # optional
      # - REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/mariadb${DOCKERCONFIGDIR:-}:/config
    # ports:
      # MariaDB listens on this port.
      # - 3306:3306
    networks:
      default:
        aliases:
          - mariadb
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
#    external: true
