# [Feed2toot](https://gitlab.com/chaica/feed2toot) automatically parses rss
# feeds, identifies new posts and posts them on the Mastodon social network.

---

services:
  feed2toot:
    image: ghcr.io/linuxserver/feed2toot
    container_name: feed2toot
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - FEED_LIMIT=5 # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/feed2toot${DOCKERCONFIGDIR:-}:/config
    # networks:
    #  default:
    #    aliases:
    #      - feed2toot
    restart: unless-stopped

# networks:
#  default:
#    name: ${NETWORK_NAME:-synobridge}
