
# [Rsnapshot](http://www.rsnapshot.org/) is a filesystem snapshot utility based
# on rsync. rsnapshot makes it easy to make periodic snapshots of local
# machines, and remote machines over ssh. The code makes extensive use of hard
# links whenever possible, to greatly reduce the disk space required.'

---

services:
  rsnapshot:
    image: ghcr.io/linuxserver/rsnapshot
    container_name: rsnapshot
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/rsnapshot:/config
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/rsnapshot/.snapshots:/.snapshots
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/rsnapshot/data:/data
    # ports:
    networks:
      default:
        aliases:
          - rsnapshot
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true