# [Piper](https://github.com/rhasspy/piper/) is a fast, local neural text to
# speech system that sounds great and is optimized for the Raspberry Pi 4. This
# container provides a Wyoming protocol server for Piper.

---

services:
  piper:
    image: ghcr.io/linuxserver/piper
    container_name: piper
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - PIPER_VOICE=en_US-lessac-medium
      # - PIPER_LENGTH=1.0 # optional
      # - PIPER_NOISE=0.667 # optional
      # - PIPER_NOISEW=0.333 # optional
      # - PIPER_SPEAKER=0 # optional
      # - PIPER_PROCS=1 # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/piper${DOCKERCONFIGDIR:-}:/config
    # ports:
      # # Wyoming connection port.
      # - 10200:10200
    networks:
      default:
        aliases:
          - piper
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
