
# [Budge](https://github.com/linuxserver/budge) is an open source 'budgeting
# with envelopes' personal finance app.

---

services:
  budge:
    image: ghcr.io/linuxserver/budge
    container_name: budge
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/budge:/config
    # ports:
      # - 80:80 # http gui
      # - 443:443 # https gui
    networks:
      default:
        aliases:
          - budge
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true