# [Audacity](https://www.audacityteam.org/) is an easy-to-use, multi-track audio
# editor and recorder. Developed by a group of volunteers as open source.

---
version: "2.1"
services:
  audacity:
    image: ghcr.io/linuxserver/audacity
    container_name: audacity
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Users home directory in the container, stores program settings and images
      - ${BASEDIR:-/volume1/docker}/audacity/config:/config
    ports:
      # Audacity desktop gui.
      - 3000:3000
      # Audacity desktop gui HTTPS.
      - 3001:3001
    restart: unless-stopped
