# [Medusa](https://pymedusa.com/) is an automatic Video Library Manager for TV
# Shows. It watches for new episodes of your favorite shows, and when they are
# posted it does its magic.

---

services:
  medusa:
    image: ghcr.io/linuxserver/medusa
    container_name: medusa
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/medusa:/config
      ${DOCKERSTORAGEDIR:-/volume1/data}:/mnt/data
    # ports:
      # The port for the Medusa webui
      # - 8081:8081
    networks:
      default:
        aliases:
          - medusa
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true