# [digiKam](https://www.digikam.org/): Professional Photo Management with the
# Power of Open Source

---

services:
  digikam:
    image: ghcr.io/linuxserver/digikam
    container_name: digikam
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - SUBFOLDER=/ # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/digikam:/config
    # ports:
      # digiKam desktop gui 
      # - 3000:3000 # optional
      # digiKam desktop gui HTTPS 
      # - 3001:3001 # optional
    networks:
      default:
        aliases:
          - digikam
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true