# [Pidgin](https://pidgin.im/) is a chat program which lets you log into
# accounts on multiple chat networks simultaneously. This means that you can be
# chatting with friends on XMPP and sitting in an IRC channel at the same time.

---

services:
  pidgin:
    image: ghcr.io/linuxserver/pidgin
    container_name: pidgin
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/pidgin:/config
    # ports:
      # Pidgin desktop gui.
      # - 3000:3000
      # Pidgin desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - pidgin
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true