
# [Netbootxyz](https://netboot.xyz) is a way to PXE boot various operating
# system installers or utilities from one place within the BIOS without the need
# of having to go retrieve the media to run the tool. iPXE is used to provide a
# user friendly menu from within the BIOS that lets you easily choose the
# operating system you want along with any specific types of versions or
# bootable flags.

---

services:
  netbootxyz:
    image: ghcr.io/linuxserver/netbootxyz
    container_name: netbootxyz
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - MENU_VERSION=1.9.9 # optional
      # - PORT_RANGE=30000:30010 # optional
      # - SUBFOLDER=/ # optional
      # - NGINX_PORT=80 # optional
      # - WEB_APP_PORT=3000 # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/netbootxyz:/config
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/netbootxyz/assets:/assets
    # ports:
      # - 3000:3000 # Web configuration interface.
      # - 69:69/udp # TFTP Port.
      # - 8080:80 # NGINX server for hosting assets. # optional
    networks:
      default:
        aliases:
          - netbootxyz
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true