# [Wireshark](https://www.wireshark.org/) is the world’s foremost and widely-
# used network protocol analyzer. It lets you see what’s happening on your
# network at a microscopic level and is the de facto (and often de jure)
# standard across many commercial and non-profit enterprises, government
# agencies, and educational institutions. Wireshark development thrives thanks
# to the volunteer contributions of networking experts around the globe and is
# the continuation of a project started by Gerald Combs in 1998.

---
version: "2.1"
services:
  wireshark:
    image: ghcr.io/linuxserver/wireshark
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Users home directory in the container, stores program settings and potentially dump files.
      - ${BASEDIR:-/volume1/docker}/wireshark/config:/config
    ports:
      # WireShark desktop gui, only use this if you are not using host mode and sniffing Docker network traffic.
      - 3000:3000 # optional
      # WireShark desktop gui HTTPS, only use this if you are not using host mode and sniffing Docker network traffic.
      - 3001:3001 # optional
    restart: unless-stopped
