# [Mstream](https://mstream.io/) is a personal music streaming server. You can
# use mStream to stream your music from your home computer to any device,
# anywhere. There are mobile apps available for both Android and iPhone.

---

services:
  mstream:
    image: ghcr.io/linuxserver/mstream
    container_name: mstream
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/mstream:/config
      - ${DOCKERSTORAGEDIR:-/volume1/data}/media:/mnt/data/media
    # ports:
      # The port for the mStream web interface
      # - 3000:3000
    networks:
      default:
        aliases:
          - mstream
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true