# [SteamOS](https://www.steamdeck.com/) is an Arch based Linux distribution made
# by Valve Software. This container is a vanilla Arch install with Steam
# repositories added for software support. **This container will only work with
# modern AMD/Intel GPUs on a real Linux Host**

---

services:
  steamos:
    image: ghcr.io/linuxserver/steamos
    container_name: steamos
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - DRINODE=/dev/dri/renderD128
      # - HOST_IP=192.168.100.10 # optional
      # - STARTUP=KDE # optional
      # - RESOLUTION=1920x1080 # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/steamos:/config
      # Optional for gamepad support. *Only working for Steam Remote Play
      # - /dev/input:/dev/input
      # Optional for gamepad support. *Only working for Steam Remote Play
      # - /run/udev/data:/run/udev/data
    # ports:
      # SteamOS desktop gui.
      # - 3000:3000
      # HTTPS SteamOS desktop gui.
      # - 3001:3001
      # Steam Remote Play Ports (UDP). 
      # - 27031-27036:27031-27036/udp # optional
      # Steam Remote Play Ports (TCP). 
      # - 27031-27036:27031-27036 # optional
      # Sunshine Ports (TCP). 
      # - 47984-47990:47984-47990 # optional
      # Sunshine Ports (TCP). 
      # - 48010-48010:48010-48010 # optional
      # Sunshine Ports (UDP). 
      # - 47998-48000:47998-48000/udp # optional
    networks:
      default:
        aliases:
          - steamos
    devices:
      # Video card passthrough to Steam.
      - /dev/dri:/dev/dri
    shm_size: "1gb"
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true