# [Ddclient](https://github.com/ddclient/ddclient) is a Perl client used to
# update dynamic DNS entries for accounts on Dynamic DNS Network Service
# Provider. It was originally written by Paul Burry and is now mostly by
# wimpunk. It has the capability to update more than just dyndns and it can
# fetch your WAN-ipaddress in a few different ways.

---
version: "2.1"
services:
  ddclient:
    image: ghcr.io/linuxserver/ddclient
    container_name: ddclient
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Persistent config files
      - ${BASEDIR:-/volume1/docker}/ddclient/config:/config
    ports:
      # Application WebUI
      - 80:80
    restart: unless-stopped
