# [Flexget](http://flexget.com/) is a multipurpose automation tool for all of
# your media.

---

services:
  flexget:
    image: ghcr.io/linuxserver/flexget
    container_name: flexget
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - FG_LOG_LEVEL=info
      - FG_LOG_FILE=/config/flexget.log
      - FG_CONFIG_FILE=/config/.flexget/config.yml
      # - FG_WEBUI_PASSWORD=info # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/flexget${DOCKERCONFIGDIR:-}:/config
      - ${DOCKERSTORAGEPATH:-/volume1/data}:${DOCKERMOUNTPATH:-/mnt/data}
    # ports:
      # # HTTP port for the WebUI.
      # - 5050:5050
    networks:
      default:
        aliases:
          - flexget
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: ${NETWORK_EXTERNAL:-false}
