
# [Flexget](http://flexget.com/) is a multipurpose automation tool for all of
# your media.

---

services:
  flexget:
    image: ghcr.io/linuxserver/flexget
    container_name: flexget
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - FG_LOG_LEVEL=info
      - FG_LOG_FILE=/config/flexget.log
      - FG_CONFIG_FILE=/config/.flexget/config.yml
      # - FG_WEBUI_PASSWORD=info # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/flexget:/config
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/flexget/data:/data
    # ports:
      # - 5050:5050 # HTTP port for the WebUI.
    networks:
      default:
        aliases:
          - flexget
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true