# [Altus](https://github.com/amanharwara/altus) is an Electron-based WhatsApp
# client with themes and multiple account support.

---

services:
  altus:
    image: ghcr.io/linuxserver/altus
    container_name: altus
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/altus${DOCKERCONFIGDIR:-}:/config
    # ports:
      # Altus desktop gui.
      # - 3000:3000
      # Altus desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - altus
    shm_size: "1gb"
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
#    external: true
