
# [Dokuwiki](https://www.dokuwiki.org/dokuwiki/) is a simple to use and highly
# versatile Open Source wiki software that doesn't require a database. It is
# loved by users for its clean and readable syntax. The ease of maintenance,
# backup and integration makes it an administrator's favorite. Built in access
# controls and authentication connectors make DokuWiki especially useful in the
# enterprise context and the large number of plugins contributed by its vibrant
# community allow for a broad range of use cases beyond a traditional wiki.

---

services:
  dokuwiki:
    image: ghcr.io/linuxserver/dokuwiki
    container_name: dokuwiki
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/dokuwiki:/config
    # ports:
      # - 80:80 # Application HTTP Port
      # - 443:443 # #optional Application HTTPS Port # optional
    networks:
      default:
        aliases:
          - dokuwiki
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true