
# [Speedtest-tracker](https://github.com/alexjustesen/speedtest-tracker) is a
# self-hosted internet performance tracking application that runs speedtest
# checks against Ookla's Speedtest service.

---

services:
  speedtest-tracker:
    image: ghcr.io/linuxserver/speedtest-tracker
    container_name: speedtest-tracker
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - APP_KEY=
      - APP_URL=
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE=
      - SPEEDTEST_SERVERS=
      # - DB_HOST= # optional
      # - DB_PORT= # optional
      # - DB_DATABASE= # optional
      # - DB_USERNAME= # optional
      # - DB_PASSWORD= # optional
      # - DISPLAY_TIMEZONE=Etc/UTC # optional
      # - PRUNE_RESULTS_OLDER_THAN=0 # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/speedtest-tracker:/config
    # ports:
      # - 80:80 # Web UI
    networks:
      default:
        aliases:
          - speedtest-tracker
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true