# [Obsidian](https://obsidian.md) is a note-taking app that lets you create,
# link, and organize your notes on your device, with hundreds of plugins and
# themes to customize your workflow. You can also publish your notes online,
# access them offline, and sync them securely with end-to-end encryption.

---
version: "2.1"
services:
  obsidian:
    image: ghcr.io/linuxserver/obsidian
    container_name: obsidian
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Users home directory in the container, stores program settings and files.
      - ${BASEDIR:-/volume1/docker}/obsidian/config:/config
    ports:
      # Obsidian desktop gui.
      - 3000:3000
      # Obsidian desktop gui HTTPS.
      - 3001:3001
    devices:
      # Add this for GL support (Linux hosts only)
      - /dev/dri:/dev/dri # optional
    shm_size: "1gb"
    restart: unless-stopped
