# [Nextcloud](https://nextcloud.com/) gives you access to all your files
# wherever you are. Where are your photos and documents? With Nextcloud you pick
# a server of your choice, at home, in a data center or at a provider. And that
# is where your files will be. Nextcloud runs on that server, protecting your
# data and giving you access from your desktop or mobile devices. Through
# Nextcloud you also access, sync and share your existing data on that FTP drive
# at the office, a Dropbox or a NAS you have at home.

---

services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/nextcloud${DOCKERCONFIGDIR:-}:/config
      - ${DOCKERSTORAGEPATH:-/volume1/data}:${DOCKERMOUNTPATH:-/mnt/data}
    # ports:
      # WebUI
      # - 443:443
    networks:
      default:
        aliases:
          - nextcloud
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
#    external: true
