# [Syncthing](https://syncthing.net) replaces proprietary sync and cloud
# services with something open, trustworthy and decentralized. Your data is your
# data alone and you deserve to choose where it is stored, if it is shared with
# some third party and how it's transmitted over the Internet.

---

services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/syncthing${DOCKERCONFIGDIR:-}:/config
      # Data1
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/syncthing/data1:/data1
      # Data2
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/syncthing/data2:/data2
    # ports:
      # # Application WebUI
      # - 8384:8384
      # # Listening port (TCP)
      # - 22000:22000/tcp
      # # Listening port (UDP)
      # - 22000:22000/udp
      # # Protocol discovery
      # - 21027:21027/udp
    networks:
      default:
        aliases:
          - syncthing
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
