# [Pwndrop](https://github.com/kgretzky/pwndrop) is a self-deployable file
# hosting service for sending out red teaming payloads or securely sharing your
# private files over HTTP and WebDAV.

---

services:
  pwndrop:
    image: ghcr.io/linuxserver/pwndrop
    container_name: pwndrop
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - SECRET_PATH=/pwndrop # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/pwndrop${DOCKERCONFIGDIR:-}:/config
    # ports:
      # web gui
      # - 8080:8080
    networks:
      default:
        aliases:
          - pwndrop
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
#    external: true
