# [GIMP](https://www.gimp.org/) is a free and open-source raster graphics editor
# used for image manipulation (retouching) and image editing, free-form drawing,
# transcoding between different image file formats, and more specialized tasks.
# It is extensible by means of plugins, and scriptable.

---

services:
  gimp:
    image: ghcr.io/linuxserver/gimp
    container_name: gimp
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/gimp${DOCKERCONFIGDIR:-}:/config
    # ports:
      # GIMP desktop gui.
      # - 3000:3000
      # GIMP desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - gimp
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}