# [WebCord](https://github.com/SpacingBat3/WebCord) can be summarized as a pack
# of security and privacy hardenings, Discord features reimplementations,
# Electron / Chromium / Discord bugs workarounds, stylesheets, internal pages
# and wrapped https://discord.com page, designed to conform with ToS as much as
# it is possible (or hide the changes that might violate it from Discord's
# eyes).

---

services:
  webcord:
    image: ghcr.io/linuxserver/webcord
    container_name: webcord
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/webcord:/config
    # ports:
      # WebCord desktop gui.
      # - 3000:3000
      # WebCord desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - webcord
    shm_size: "1gb"
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true