
# [Fail2ban](http://www.fail2ban.org/) is a daemon to ban hosts that cause
# multiple authentication errors.

---

services:
  fail2ban:
    image: ghcr.io/linuxserver/fail2ban
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    # network_mode: host
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - VERBOSITY=-vv # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/fail2ban:/config
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/fail2ban/var/log:ro:/var/log:ro
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/fail2ban/remotelogs/airsonic:ro:/remotelogs/airsonic:ro
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/fail2ban/remotelogs/apache2:ro:/remotelogs/apache2:ro
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/fail2ban/remotelogs/authelia:ro:/remotelogs/authelia:ro
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/fail2ban/remotelogs/emby:ro:/remotelogs/emby:ro
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/fail2ban/remotelogs/filebrowser:ro:/remotelogs/filebrowser:ro
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/fail2ban/remotelogs/homeassistant:ro:/remotelogs/homeassistant:ro
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/fail2ban/remotelogs/lighttpd:ro:/remotelogs/lighttpd:ro
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/fail2ban/remotelogs/nextcloud:ro:/remotelogs/nextcloud:ro
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/fail2ban/remotelogs/nginx:ro:/remotelogs/nginx:ro
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/fail2ban/remotelogs/nzbget:ro:/remotelogs/nzbget:ro
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/fail2ban/remotelogs/overseerr:ro:/remotelogs/overseerr:ro
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/fail2ban/remotelogs/prowlarr:ro:/remotelogs/prowlarr:ro
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/fail2ban/remotelogs/radarr:ro:/remotelogs/radarr:ro
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/fail2ban/remotelogs/sabnzbd:ro:/remotelogs/sabnzbd:ro
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/fail2ban/remotelogs/sonarr:ro:/remotelogs/sonarr:ro
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/fail2ban/remotelogs/unificontroller:ro:/remotelogs/unificontroller:ro
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/fail2ban/remotelogs/vaultwarden:ro:/remotelogs/vaultwarden:ro
    ports:
      - 80:80 # Application WebUI
    networks:
      default:
        aliases:
          - fail2ban
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true