# [Planka](https://github.com/plankanban/planka/) is an elegant open source
# project tracking tool.

---

services:
  planka:
    image: ghcr.io/linuxserver/planka
    container_name: planka
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - BASE_URL=https://planka.example.com
      - DATABASE_URL=postgresql://user:password@planka-db:5432/planka
      - DEFAULT_ADMIN_EMAIL=demo@demo.demo
      - DEFAULT_ADMIN_USERNAME=demo
      - DEFAULT_ADMIN_PASSWORD=demo
      - DEFAULT_ADMIN_NAME=Demo User
      - SECRET_KEY=notasecretkey
      - TRUST_PROXY=0
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/planka:/config
    # ports:
      # Planka web UI.
      # - 1337:1337
    networks:
      default:
        aliases:
          - planka
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}