# This container needs special attention. Please check https://hub.docker.com/r/linuxserver/qemu-static for details.
---
version: "2.1"
services:
  qemu-static:
    image: ghcr.io/linuxserver/qemu-static
    container_name: qemu-static
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Configuration files.
      - ${BASEDIR:-/volume1/docker}/qemu-static/config:/config
    ports:
    restart: unless-stopped
