# [BOINC](https://boinc.berkeley.edu/) is a platform for high-throughput
# computing on a large scale (thousands or millions of computers). It can be
# used for volunteer computing (using consumer devices) or grid computing (using
# organizational resources). It supports virtualized, parallel, and GPU-based
# applications.

---

services:
  boinc:
    image: ghcr.io/linuxserver/boinc
    container_name: boinc
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - PASSWORD= # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/boinc${DOCKERCONFIGDIR:-}:/config
    # ports:
      # # Boinc desktop gui.
      # - 8080:8080
      # # Boinc desktop gui HTTPS.
      # - 8181:8181
    networks:
      default:
        aliases:
          - boinc
    devices:
      # # Only needed if you want to use your Intel GPU (vaapi).
      # - /dev/dri:/dev/dri # optional
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
