# [Piwigo](http://piwigo.org/) is a photo gallery software for the web that
# comes with powerful features to publish and manage your collection of
# pictures.

---

services:
  piwigo:
    image: ghcr.io/linuxserver/piwigo
    container_name: piwigo
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/piwigo${DOCKERCONFIGDIR:-}:/config
      # Image storage for Piwigo
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/piwigo/gallery:/gallery
    # ports:
      # # Application WebUI
      # - 80:80
    networks:
      default:
        aliases:
          - piwigo
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: ${NETWORK_EXTERNAL:-false}
