# [Wikijs](https://github.com/Requarks/wiki) A modern, lightweight and powerful
# wiki app built on NodeJS.

---

services:
  wikijs:
    image: ghcr.io/linuxserver/wikijs
    container_name: wikijs
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - DB_TYPE=sqlite # optional
      # - DB_HOST= # optional
      # - DB_PORT= # optional
      # - DB_NAME= # optional
      # - DB_USER= # optional
      # - DB_PASS= # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/wikijs${DOCKERCONFIGDIR:-}:/config
      - ${DOCKERSTORAGEPATH:-/volume1/data}:${DOCKERMOUNTPATH:-/mnt/data}
    # ports:
      # # Port for Wiki.js's web interface.
      # - 3000:3000
    networks:
      default:
        aliases:
          - wikijs
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: ${NETWORK_EXTERNAL:-false}
