
# [Series Troxide](https://github.com/MaarifaMaarifa/series-troxide) a Simple
# and Modern Series Tracker

---

services:
  series-troxide:
    image: ghcr.io/linuxserver/series-troxide
    container_name: series-troxide
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/series-troxide:/config
    # ports:
      # - 3000:3000 # Series Troxide desktop gui.
      # - 3001:3001 # HTTPS Series Troxide desktop gui.
    networks:
      default:
        aliases:
          - series-troxide
    shm_size: "1gb"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true