# [Series Troxide](https://github.com/MaarifaMaarifa/series-troxide) a Simple
# and Modern Series Tracker

---

services:
  series-troxide:
    image: ghcr.io/linuxserver/series-troxide
    container_name: series-troxide
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/series-troxide${DOCKERCONFIGDIR:-}:/config
    # ports:
      # Series Troxide desktop gui.
      # - 3000:3000
      # HTTPS Series Troxide desktop gui.
      # - 3001:3001
    networks:
      default:
        aliases:
          - series-troxide
    shm_size: "1gb"
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
#    external: true
