# [DB Browser for SQLite](https://sqlitebrowser.org/) is a high quality, visual,
# open source tool to create, design, and edit database files compatible with
# SQLite.

---

services:
  sqlitebrowser:
    image: ghcr.io/linuxserver/sqlitebrowser
    container_name: sqlitebrowser
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/sqlitebrowser:/config
    # ports:
      # Sqlitebrowser desktop gui.
      # - 3000:3000
      # Sqlitebrowser desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - sqlitebrowser
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true