
# [Smokeping](https://oss.oetiker.ch/smokeping/) keeps track of your network
# latency. For a full example of what this application is capable of visit
# [UCDavis](http://smokeping.ucdavis.edu/cgi-bin/smokeping.fcgi).

---

services:
  smokeping:
    image: ghcr.io/linuxserver/smokeping
    container_name: smokeping
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - MASTER_URL=http://<master-host-ip>:80/smokeping/ # optional
      # - SHARED_SECRET=password # optional
      # - CACHE_DIR=/tmp # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/smokeping:/config
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/smokeping/data:/data
    # ports:
      # - 80:80 # Allows HTTP access to the internal webserver.
    networks:
      default:
        aliases:
          - smokeping
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true