# [Github Desktop](https://desktop.github.com/) is an open source Electron-based
# GitHub app. It is written in TypeScript and uses React.

---

services:
  github-desktop:
    image: ghcr.io/linuxserver/github-desktop
    container_name: github-desktop
    cap_add:
      - IPC_LOCK
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/github-desktop${DOCKERCONFIGDIR:-}:/config
    # ports:
      # # Github Desktop gui.
      # - 3000:3000
      # # HTTPS Github Desktop gui.
      # - 3001:3001
    networks:
      default:
        aliases:
          - github-desktop
    shm_size: "1gb"
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: ${NETWORK_EXTERNAL:-false}
