# This container needs special attention. Please check https://hub.docker.com/r/linuxserver/yq for details.
---

services:
  yq:
    image: ghcr.io/linuxserver/yq
    container_name: yq
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/yq${DOCKERCONFIGDIR:-}:/config
    # ports:
    networks:
      default:
        aliases:
          - yq
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}