# This container needs special attention. Please check https://hub.docker.com/r/linuxserver/yq for details.
---
version: "2.1"
services:
  yq:
    image: ghcr.io/linuxserver/yq
    container_name: yq
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # specify a timezone to use, see this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Configuration files.
      - ${BASEDIR:-/volume1/docker}/yq/config:/config
    ports:
      # Plex WebUI
      - 32400:32400
    restart: unless-stopped
