
# [Luanti](https://www.luanti.org/) (formerly Minetest) is an open source voxel
# game-creation platform with easy modding and game creation

---

services:
  luanti:
    image: ghcr.io/linuxserver/luanti
    container_name: luanti
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - CLI_ARGS=--gameid devtest # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/luanti/config/.minetest:/config/.minetest
    # ports:
      # - 30000:30000/udp # Port Luanti listens on (UDP).
    networks:
      default:
        aliases:
          - luanti
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true