# [KeePassXC](https://keepassxc.org/) is a free and open-source password
# manager. It started as a community fork of KeePassX (itself a cross-platform
# port of KeePass).

---

services:
  keepassxc:
    image: ghcr.io/linuxserver/keepassxc
    container_name: keepassxc
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/keepassxc${DOCKERCONFIGDIR:-}:/config
    # ports:
      # # KeePassXC desktop gui.
      # - 3000:3000
      # # KeePassXC desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - keepassxc
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: ${NETWORK_EXTERNAL:-false}
