# # This container needs special attention. Please check
# https://hub.docker.com/r/linuxserver/ffmpeg for details.

---

services:
  ffmpeg:
    image: ghcr.io/linuxserver/ffmpeg
    container_name: ffmpeg
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/ffmpeg${DOCKERCONFIGDIR:-}:/config
    # ports:
      # Application WebUI
      # - 80:80
    networks:
      default:
        aliases:
          - ffmpeg
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
#    external: true
