# [hiSHtory](https://github.com/ddworken/hishtory) is a better shell history. It
# stores your shell history in context (what directory you ran the command in,
# whether it succeeded or failed, how long it took, etc). This is all stored
# locally and end-to-end encrypted for syncing to to all your other computers.

---

services:
  hishtory-server:
    image: ghcr.io/linuxserver/hishtory-server
    container_name: hishtory-server
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - HISHTORY_POSTGRES_DB=postgresql://${HISHTORY_DB_USER}:${HISHTORY_DB_PASS}@hishtory-db:5432/hishtory?sslmode=disable # optional
      # - HISHTORY_SQLITE_DB=/config/hishtory.db # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/hishtory-server${DOCKERCONFIGDIR:-}:/config
    # ports:
      # # API port
      # - 8080:8080
    networks:
      default:
        aliases:
          - hishtory-server
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
