# [Ferdium](https://ferdium.org/) is a desktop app that helps you organize how
# you use your favourite apps by combining them into one application.

---

services:
  ferdium:
    image: ghcr.io/linuxserver/ferdium
    container_name: ferdium
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/ferdium:/config
    # ports:
      # Ferdium desktop gui.
      # - 3000:3000
      # Ferdium desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - ferdium
    shm_size: "1gb"
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}