# [HedgeDoc](https://hedgedoc.org/) gives you access to all your files wherever
# you are. HedgeDoc is a real-time, multi-platform collaborative markdown note
# editor. This means that you can write notes with other people on your desktop,
# tablet or even on the phone. You can sign-in via multiple auth providers like
# Facebook, Twitter, GitHub and many more on the homepage.

---

services:
  hedgedoc:
    image: ghcr.io/linuxserver/hedgedoc
    container_name: hedgedoc
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - DB_HOST=<hostname or ip>
      - DB_PORT=3306
      - DB_USER=hedgedoc
      - DB_PASS=<secret password>
      - DB_NAME=hedgedoc
      - CMD_DOMAIN=localhost
      # - CMD_URL_ADDPORT=false # optional
      # - CMD_PROTOCOL_USESSL=false # optional
      # - CMD_PORT=3000 # optional
      # - CMD_ALLOW_ORIGIN=['localhost'] # optional
      # - CMD_DB_DIALECT= # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/hedgedoc${DOCKERCONFIGDIR:-}:/config
    # ports:
      # # Web gui port (internal port also needs to be changed if accessing at port other than 80, 443 and 3000).
      # - 3000:3000
    networks:
      default:
        aliases:
          - hedgedoc
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
