# [Orca Slicer](https://github.com/SoftFever/OrcaSlicer) is an open source
# slicer for FDM printers. OrcaSlicer is fork of Bambu Studio, it was previously
# known as BambuStudio-SoftFever, Bambu Studio is forked from PrusaSlicer by
# Prusa Research, which is from Slic3r by Alessandro Ranellucci and the RepRap
# community

---

services:
  orcaslicer:
    image: ghcr.io/linuxserver/orcaslicer
    container_name: orcaslicer
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/orcaslicer${DOCKERCONFIGDIR:-}:/config
    # ports:
      # Orca Slicer desktop gui.
      # - 3000:3000
      # Orca Slicer desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - orcaslicer
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
#    external: true
