
# [Nginx](https://nginx.org/) is a simple webserver with php support. The config
# files reside in `/config` for easy user customization.

---

services:
  nginx:
    image: ghcr.io/linuxserver/nginx
    container_name: nginx
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/nginx:/config
    # ports:
      # - 80:80 # http
      # - 443:443 # https
    networks:
      default:
        aliases:
          - nginx
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true