# [Webgrabplus](https://www.webgrabplus.com) is a multi-site incremental xmltv
# epg grabber. It collects tv-program guide data from selected tvguide sites for
# your favourite channels.

---

services:
  webgrabplus:
    image: ghcr.io/linuxserver/webgrabplus
    container_name: webgrabplus
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/webgrabplus:/config
      # Where webgrabplus should store it's data files.
      ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/webgrabplus/data:/data
    # ports:
    networks:
      default:
        aliases:
          - webgrabplus
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true