
# [Deluge](http://deluge-torrent.org/) is a lightweight, Free Software, cross-
# platform BitTorrent client. * Full Encryption * WebUI * Plugin System * Much
# more...

---

services:
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - DELUGE_LOGLEVEL=error # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/deluge:/config
      - ${DOCKERSTORAGEDIR:-/volume1/data}/downloads:/mnt/data/downloads
    # ports:
      # - 8112:8112 # Port for webui
      # - 6881:6881 # Inbound torrent traffic (See App Setup)
      # - 6881:6881/udp # Inbound torrent traffic (See App Setup)
      # - 58846:58846 # Default deluged port for thin client connectivity # optional
    networks:
      default:
        aliases:
          - deluge
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true