# [Folding@home](https://foldingathome.org/) is a distributed computing project
# for simulating protein dynamics, including the process of protein folding and
# the movements of proteins implicated in a variety of diseases. It brings
# together citizen scientists who volunteer to run simulations of protein
# dynamics on their personal computers. Insights from this data are helping
# scientists to better understand biology, and providing new opportunities for
# developing therapeutics.

---

services:
  foldingathome:
    image: ghcr.io/linuxserver/foldingathome
    container_name: foldingathome
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - ACCOUNT_TOKEN=
      - MACHINE_NAME=
      # - CLI_ARGS= # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/foldingathome${DOCKERCONFIGDIR:-}:/config
    # ports:
      # # Application WebUI
      # - 80:80
      # # Folding@home web gui (redirects to [https://app.foldingathome.org](https://app.foldingathome.org)).
      # - 7396:7396 # optional
    networks:
      default:
        aliases:
          - foldingathome
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: ${NETWORK_EXTERNAL:-false}
