# [Htpcmanager](https://github.com/HTPC-Manager/HTPC-Manager) is a front end for
# many htpc related applications.

---

services:
  htpcmanager:
    image: ghcr.io/linuxserver/htpcmanager
    container_name: htpcmanager
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/htpcmanager:/config
    # ports:
      # Application WebUI
      # - 8085:8085
    networks:
      default:
        aliases:
          - htpcmanager
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true