
# [pyLoad](https://pyload.net/) is a Free and Open Source download manager
# written in Python and designed to be extremely lightweight, easily extensible
# and fully manageable via web.

---

services:
  pyload-ng:
    image: ghcr.io/linuxserver/pyload-ng
    container_name: pyload-ng
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/pyload-ng:/config
      - ${DOCKERSTORAGEDIR:-/volume1/data}/downloads:/mnt/data/downloads
    # ports:
      # - 8000:8000 # Allows HTTP access to the application
      # - 9666:9666 # Click'n'Load port. # optional
    networks:
      default:
        aliases:
          - pyload-ng
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true