
# [Lazylibrarian](https://lazylibrarian.gitlab.io/) is a program to follow
# authors and grab metadata for all your digital reading needs. It uses a
# combination of Goodreads Librarything and optionally GoogleBooks as sources
# for author info and book info. This container is based on the DobyTang fork.

---

services:
  lazylibrarian:
    image: ghcr.io/linuxserver/lazylibrarian
    container_name: lazylibrarian
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - DOCKER_MODS=linuxserver/mods:universal-calibre|linuxserver/mods:lazylibrarian-ffmpeg # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/lazylibrarian:/config
      - ${DOCKERSTORAGEDIR:-/volume1/data}/downloads:/mnt/data/downloads
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/lazylibrarian/books:/books
    # ports:
      # - 5299:5299 # The port for the LazyLibrarian webinterface
    networks:
      default:
        aliases:
          - lazylibrarian
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true