# [Mastodon](https://github.com/mastodon/mastodon/) is a free, open-source
# social network server based on ActivityPub where users can follow friends and
# discover new ones..

---

services:
  mastodon:
    image: ghcr.io/linuxserver/mastodon
    container_name: mastodon
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - LOCAL_DOMAIN=example.com
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=db
      - DB_USER=mastodon
      - DB_NAME=mastodon
      - DB_PASS=mastodon
      - DB_PORT=5432
      - ES_ENABLED=false
      - ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY=
      - ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY=
      - ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT=
      - SECRET_KEY_BASE=
      - OTP_SECRET=
      - VAPID_PRIVATE_KEY=
      - VAPID_PUBLIC_KEY=
      - SMTP_SERVER=mail.example.com
      - SMTP_PORT=25
      - SMTP_LOGIN=
      - SMTP_PASSWORD=
      - SMTP_FROM_ADDRESS=notifications@example.com
      - S3_ENABLED=false
      # - WEB_DOMAIN=mastodon.example.com # optional
      # - ES_HOST=es # optional
      # - ES_PORT=9200 # optional
      # - ES_USER=elastic # optional
      # - ES_PASS=elastic # optional
      # - S3_BUCKET= # optional
      # - AWS_ACCESS_KEY_ID= # optional
      # - AWS_SECRET_ACCESS_KEY= # optional
      # - S3_ALIAS_HOST= # optional
      # - SIDEKIQ_ONLY=false # optional
      # - SIDEKIQ_QUEUE= # optional
      # - SIDEKIQ_DEFAULT=false # optional
      # - SIDEKIQ_THREADS=5 # optional
      # - DB_POOL=5 # optional
      # - NO_CHOWN= # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/mastodon:/config
    # ports:
      # Port for web frontend
      # - 80:80
      # Port for web frontend
      # - 443:443
    networks:
      default:
        aliases:
          - mastodon
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}