# [Limnoria](https://github.com/ProgVal/limnoria) A robust, full-featured, and
# user/programmer-friendly Python IRC bot, with many existing plugins. Successor
# of the well-known Supybot.

---
version: "2.1"
services:
  limnoria:
    image: ghcr.io/linuxserver/limnoria
    container_name: limnoria
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Persistent config files
      - ${BASEDIR:-/volume1/docker}/limnoria/config:/config
    ports:
      # Port for Limnoria's web interface.
      - 8080:8080
    restart: unless-stopped
