
# [VSCodium](https://vscodium.com/) is a community-driven, freely-licensed
# binary distribution of Microsoft’s editor VS Code.

---

services:
  vscodium:
    image: ghcr.io/linuxserver/vscodium
    container_name: vscodium
    cap_add:
      - IPC_LOCK
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/vscodium:/config
    # ports:
      # - 3000:3000 # VSCodium desktop gui.
      # - 3001:3001 # HTTPS VSCodium desktop gui.
    networks:
      default:
        aliases:
          - vscodium
    shm_size: "1gb"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true