# [VSCodium](https://vscodium.com/) is a community-driven, freely-licensed
# binary distribution of Microsoft’s editor VS Code.

---

services:
  vscodium:
    image: ghcr.io/linuxserver/vscodium
    container_name: vscodium
    cap_add:
      - IPC_LOCK
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/vscodium${DOCKERCONFIGDIR:-}:/config
    # ports:
      # VSCodium desktop gui.
      # - 3000:3000
      # HTTPS VSCodium desktop gui.
      # - 3001:3001
    networks:
      default:
        aliases:
          - vscodium
    shm_size: "1gb"
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
#    external: true
