# [Microsoft Edge](https://www.microsoft.com/edge) is a cross-platform web
# browser developed by Microsoft and based on Chromium.

---

services:
  msedge:
    image: ghcr.io/linuxserver/msedge
    container_name: msedge
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - EDGE_CLI=https://www.linuxserver.io/ # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/msedge${DOCKERCONFIGDIR:-}:/config
    # ports:
      # # Edge desktop gui.
      # - 3000:3000
      # # HTTPS Edge desktop gui.
      # - 3001:3001
    networks:
      default:
        aliases:
          - msedge
    shm_size: "1gb"
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: ${NETWORK_EXTERNAL:-false}
