# [Synclounge](https://github.com/samcm/synclounge) is a third party tool that
# allows you to watch Plex in sync with your friends/family, wherever you are.

---

services:
  synclounge:
    image: ghcr.io/linuxserver/synclounge
    container_name: synclounge
    environment:
      # - AUTH_LIST=plexuser1,plexuser2,email1,machineid1 # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/synclounge${DOCKERCONFIGDIR:-}:/config
    # ports:
      # Web app and server port
      # - 8088:8088
    networks:
      default:
        aliases:
          - synclounge
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}