
# [Kdenlive](https://kdenlive.org/) is a powerful free and open source cross-
# platform video editing program made by the KDE community. Feature rich and
# production ready.

---

services:
  kdenlive:
    image: ghcr.io/linuxserver/kdenlive
    container_name: kdenlive
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - SUBFOLDER=/ # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/kdenlive:/config
    # ports:
      # - 3000:3000 # Kdenlive desktop gui
      # - 3001:3001 # Kdenlive desktop gui HTTPS
    networks:
      default:
        aliases:
          - kdenlive
    devices:
      # Add this for hardware acceleration (Linux hosts only)
      - /dev/dri:/dev/dri # optional
    shm_size: "1gb" # optional
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true