# [Oscam](https://git.streamboard.tv/common/oscam) is an Open Source Conditional
# Access Module software used for descrambling DVB transmissions using smart
# cards. It's both a server and a client.

---

services:
  oscam:
    image: ghcr.io/linuxserver/oscam
    container_name: oscam
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/oscam:/config
    # ports:
      # WebUI
      # - 8888:8888
    networks:
      default:
        aliases:
          - oscam
    devices:
      # For passing through smart card readers.
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true