# [Snapdrop](https://github.com/snapdrop/snapdrop) A local file sharing in your
# browser. Inspired by Apple's Airdrop.

---

services:
  snapdrop:
    image: ghcr.io/linuxserver/snapdrop
    container_name: snapdrop
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/snapdrop${DOCKERCONFIGDIR:-}:/config
    # ports:
      # http gui
      # - 80:80
      # https gui
      # - 443:443
    networks:
      default:
        aliases:
          - snapdrop
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}