# [Lidarr](https://github.com/lidarr/Lidarr) is a music collection manager for
# Usenet and BitTorrent users. It can monitor multiple RSS feeds for new tracks
# from your favorite artists and will grab, sort and rename them. It can also be
# configured to automatically upgrade the quality of files already downloaded
# when a better quality format becomes available.

---

services:
  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/lidarr:/config
      - ${DOCKERSTORAGEDIR:-/volume1/data}:/mnt/data
    # ports:
      # Application WebUI
      # - 8686:8686
    networks:
      default:
        aliases:
          - lidarr
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}