
# This container needs special attention. Please check https://hub.docker.com/r/linuxserver/modmanager for details.
---

services:
  modmanager:
    image: ghcr.io/linuxserver/modmanager
    container_name: modmanager
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/modmanager:/config
    # ports:
      # - 80:80 # Application WebUI
    networks:
      default:
        aliases:
          - modmanager
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true