# [Zotero](https://www.zotero.org/) is a free, easy-to-use tool to help you
# collect, organize, annotate, cite, and share research.

---

services:
  zotero:
    image: ghcr.io/linuxserver/zotero
    container_name: zotero
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/zotero:/config
    # ports:
      # Zotero gui.
      # - 3000:3000
      # HTTPS Zotero gui.
      # - 3001:3001
    networks:
      default:
        aliases:
          - zotero
    shm_size: "1gb"
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true