# [Phpmyadmin](https://github.com/phpmyadmin/phpmyadmin/) is a free software
# tool written in PHP, intended to handle the administration of MySQL over the
# Web. phpMyAdmin supports a wide range of operations on MySQL and MariaDB.

---

services:
  phpmyadmin:
    image: ghcr.io/linuxserver/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - PMA_ARBITRARY=1 # optional
      # - PMA_ABSOLUTE_URI=https://phpmyadmin.example.com # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/phpmyadmin:/config
    # ports:
      # Port for web frontend
      # - 80:80
    networks:
      default:
        aliases:
          - phpmyadmin
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true