# [MediaElch](https://github.com/Komet/MediaElch) is a MediaManager for Kodi.
# Information about Movies, TV Shows, Concerts and Music are stored as nfo
# files. Fanarts are downloaded automatically from fanart.tv. Using the nfo
# generator, MediaElch can be used with other MediaCenters as well.

---

services:
  mediaelch:
    image: ghcr.io/linuxserver/mediaelch
    container_name: mediaelch
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/mediaelch${DOCKERCONFIGDIR:-}:/config
    # ports:
      # # MediaElch desktop gui.
      # - 3000:3000
      # # MediaElch desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - mediaelch
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: ${NETWORK_EXTERNAL:-false}
