# This container needs special attention. Please check https://hub.docker.com/r/linuxserver/build-agent for details.
---

services:
  build-agent:
    image: ghcr.io/linuxserver/build-agent
    container_name: build-agent
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/build-agent:/config
    # ports:
      # Application WebUI
      # - 80:80
    networks:
      default:
        aliases:
          - build-agent
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true