# [Minisatip](https://github.com/catalinii/minisatip) is a multi-threaded satip
# server version 1.2 that runs under Linux and it was tested with DVB-S, DVB-S2,
# DVB-T, DVB-T2, DVB-C, DVB-C2, ATSC and ISDB-T cards.

---
version: "2.1"
services:
  minisatip:
    image: ghcr.io/linuxserver/minisatip
    container_name: minisatip
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
      # Specify specific run params for minisatip
      - RUN_OPTS=
    volumes:
      # Configuration files and minisatip data
      - ${BASEDIR:-/volume1/docker}/minisatip/config:/config
    ports:
      # Status Page WebUI
      - 8875:8875
      # RTSP Port
      - 554:554
      # App Discovery
      - 1900:1900/udp
    devices:
      # For passing through Tv-cards
      - /dev/dvb:/dev/dvb
    restart: unless-stopped
