# [Calibre](https://calibre-ebook.com/) is a powerful and easy to use e-book
# manager. Users say it's outstanding and a must-have. It'll allow you to do
# nearly everything and it takes things a step beyond normal e-book software.
# It's also completely free and open source and great for both casual users and
# computer experts.

---

services:
  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - PASSWORD= # optional
      # - CLI_ARGS= # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/calibre:/config
    # ports:
      # Calibre desktop gui.
      # - 8080:8080
      # Calibre desktop gui HTTPS.
      # - 8181:8181
      # Calibre webserver gui.
      # - 8081:8081
    networks:
      default:
        aliases:
          - calibre
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true