# [Ddclient](https://github.com/ddclient/ddclient) is a Perl client used to
# update dynamic DNS entries for accounts on Dynamic DNS Network Service
# Provider. It was originally written by Paul Burry and is now mostly by
# wimpunk. It has the capability to update more than just dyndns and it can
# fetch your WAN-ipaddress in a few different ways.

---

services:
  ddclient:
    image: ghcr.io/linuxserver/ddclient
    container_name: ddclient
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/ddclient:/config
    # ports:
      # Application WebUI
      # - 80:80
    networks:
      default:
        aliases:
          - ddclient
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true