# [Habridge](https://github.com/bwssytems/ha-bridge/) emulates Philips Hue API
# to other home automation gateways such as an Amazon Echo/Dot Gen 1 (gen 2 has
# issues discovering ha-bridge) or other systems that support Philips Hue. The
# Bridge handles basic commands such as 'On', 'Off' and 'brightness' commands of
# the hue protocol. This bridge can control most devices that have a distinct
# API.

---
version: "2.1"
services:
  habridge:
    image: ghcr.io/linuxserver/habridge
    container_name: habridge
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
      # Key used to secure communication.
      - SEC_KEY=
    volumes:
      # Where HABridge stores config files and data.
      - ${BASEDIR:-/volume1/docker}/habridge/config:/config
    ports:
      # WebUI
      - 8080:8080
      # HABridge communication port.
      - 50000:50000
    restart: unless-stopped
