# [LibreWolf](https://librewolf.net/) is a custom and independent version of
# Firefox, with the primary goals of privacy, security and user freedom.
# LibreWolf also aims to remove all the telemetry, data collection and
# annoyances, as well as disabling anti-freedom features like DRM.

---

services:
  librewolf:
    image: ghcr.io/linuxserver/librewolf
    container_name: librewolf
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - LIBREWOLF_CLI=https://www.linuxserver.io/ # optional
    volumes:
      ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/librewolf:/config
    # ports:
      # LibreWolf desktop gui.
      # - 3000:3000
      # LibreWolf desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - librewolf
    shm_size: "1gb"
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true