# [Your_spotify](https://github.com/Yooooomi/your_spotify) is a self-hosted
# application that tracks what you listen and offers you a dashboard to explore
# statistics about it! It's composed of a web server which polls the Spotify API
# every now and then and a web application on which you can explore your
# statistics.

---

services:
  your_spotify:
    image: ghcr.io/linuxserver/your_spotify
    container_name: your_spotify
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - APP_URL=http://localhost
      - SPOTIFY_PUBLIC=
      - SPOTIFY_SECRET=
      - CORS=http://localhost:80,https://localhost:443
      - MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/your_spotify${DOCKERCONFIGDIR:-}:/config
    # ports:
      # your_spotify HTTP webui
      # - 80:80
      # your_spotify HTTPS webui
      # - 443:443
    networks:
      default:
        aliases:
          - your_spotify
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
#    external: true
