# [Ubooquity](https://vaemendis.net/ubooquity/) is a free, lightweight and easy-
# to-use home server for your comics and ebooks. Use it to access your files
# from anywhere, with a tablet, an e-reader, a phone or a computer.

---

services:
  ubooquity:
    image: ghcr.io/linuxserver/ubooquity
    container_name: ubooquity
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - MAXMEM= # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/ubooquity:/config
      # Location of books.
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/ubooquity/books:/books
      # Location of comics.
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/ubooquity/comics:/comics
      # Location of raw files.
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/ubooquity/files:/files
    # ports:
      # The library port.
      # - 2202:2202
      # The admin port.
      # - 2203:2203
    networks:
      default:
        aliases:
          - ubooquity
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}