# The [Mullvad Browser](https://mullvad.net/en/browser) is a privacy-focused web
# browser developed in a collaboration between Mullvad VPN and the Tor Project.
# It’s designed to minimize tracking and fingerprinting. You could say it’s a
# Tor Browser to use without the Tor Network. Instead, you can use it with a
# trustworthy VPN.

---

services:
  mullvad-browser:
    image: ghcr.io/linuxserver/mullvad-browser
    container_name: mullvad-browser
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - LOCAL_NET=192.168.0.0/16 # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/mullvad-browser${DOCKERCONFIGDIR:-}:/config
    # ports:
      # # Mullvad Browser GUI.
      # - 3000:3000
      # # Mullvad Browser GUI HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - mullvad-browser
    shm_size: "1gb"
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
