# [Overseerr](https://overseerr.dev/) is a request management and media
# discovery tool built to work with your existing Plex ecosystem.

---
version: "2.1"
services:
  overseerr:
    image: ghcr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Persistent config files
      - ${BASEDIR:-/volume1/docker}/overseerr/config:/config
    ports:
      # Port for Overseerr's web interface.
      - 5055:5055
    restart: unless-stopped
