
# [LibreOffice](https://www.libreoffice.org/) is a free and powerful office
# suite, and a successor to OpenOffice.org (commonly known as OpenOffice). Its
# clean interface and feature-rich tools help you unleash your creativity and
# enhance your productivity.

---

services:
  libreoffice:
    image: ghcr.io/linuxserver/libreoffice
    container_name: libreoffice
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/libreoffice:/config
    # ports:
      # - 3000:3000 # LibreOffice desktop gui.
      # - 3001:3001 # LibreOffice desktop gui HTTPS.
    networks:
      default:
        aliases:
          - libreoffice
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true