
# [Minisatip](https://github.com/catalinii/minisatip) is a multi-threaded satip
# server version 1.2 that runs under Linux and it was tested with DVB-S, DVB-S2,
# DVB-T, DVB-T2, DVB-C, DVB-C2, ATSC and ISDB-T cards.

---

services:
  minisatip:
    image: ghcr.io/linuxserver/minisatip
    container_name: minisatip
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - RUN_OPTS=
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/minisatip:/config
    # ports:
      # - 8875:8875 # Status Page WebUI
      # - 554:554 # RTSP Port
      # - 1900:1900/udp # App Discovery
    networks:
      default:
        aliases:
          - minisatip
    devices:
      # For passing through Tv-cards
      - /dev/dvb:/dev/dvb
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true