# [WPS Office](https://www.wps.com/) is a lightweight, feature-rich
# comprehensive office suite with high compatibility. As a handy and
# professional office software, WPS Office allows you to edit files in Writer,
# Presentation, Spreadsheet, and PDF to improve your work efficiency.

---

services:
  wps-office:
    image: ghcr.io/linuxserver/wps-office
    container_name: wps-office
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/wps-office:/config
    # ports:
      # WPS Office desktop gui.
      # - 3000:3000
      # WPS Office desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - wps-office
    shm_size: "1gb"
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true