# [LibreOffice](https://www.libreoffice.org/) is a free and powerful office
# suite, and a successor to OpenOffice.org (commonly known as OpenOffice). Its
# clean interface and feature-rich tools help you unleash your creativity and
# enhance your productivity.

---
version: "2.1"
services:
  libreoffice:
    image: ghcr.io/linuxserver/libreoffice
    container_name: libreoffice
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Users home directory in the container, stores program settings and documents
      - ${BASEDIR:-/volume1/docker}/libreoffice/config:/config
    ports:
      # LibreOffice desktop gui.
      - 3000:3000
      # LibreOffice desktop gui HTTPS.
      - 3001:3001
    restart: unless-stopped
