# [Limnoria](https://github.com/ProgVal/limnoria) A robust, full-featured, and
# user/programmer-friendly Python IRC bot, with many existing plugins. Successor
# of the well-known Supybot.

---

services:
  limnoria:
    image: ghcr.io/linuxserver/limnoria
    container_name: limnoria
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/limnoria${DOCKERCONFIGDIR:-}:/config
    # ports:
      # # Port for Limnoria's web interface.
      # - 8080:8080
    networks:
      default:
        aliases:
          - limnoria
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
