
# [syslog-ng](https://www.syslog-ng.com/products/open-source-log-management/)
# allows you to flexibly collect, parse, classify, rewrite and correlate logs
# from across your infrastructure and store or route them to log analysis tools.

---

services:
  syslog-ng:
    image: ghcr.io/linuxserver/syslog-ng
    container_name: syslog-ng
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - LOG_TO_STDOUT= # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/syslog-ng:/config
      # Stores logs collected by the syslog-ng service
      - /var/log:/var/log
    # ports:
      # - 514:5514/udp # Syslog UDP
      # - 601:6601/tcp # Syslog TCP
      # - 6514:6514/tcp # Syslog TLS
    networks:
      default:
        aliases:
          - syslog-ng
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true