# [Flexget](http://flexget.com/) is a multipurpose automation tool for all of
# your media.

---
version: "2.1"
services:
  flexget:
    image: ghcr.io/linuxserver/flexget
    container_name: flexget
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # specify a timezone to use, see this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
      - TZ=${TZ:-Europe/Amsterdam}
      # Set the FlexGet logging level.
      - FG_LOG_LEVEL=info
      # Set the FlexGet log file location.
      - FG_LOG_FILE=/config/flexget.log
      # Set the FlexGet config file location.
      - FG_CONFIG_FILE=/config/.flexget/config.yml
      # Set the FlexGet webui password. Pay attention to Bash/YAML reserved characters.
      - FG_WEBUI_PASSWORD=info # optional
    volumes:
      # Local path for FlexGet config files.
      - ${BASEDIR:-/volume1/docker}/flexget/config:/config
      # Default path for downloads.
      - ${BASEDIR:-/volume1/docker}/flexget/data:/data # optional
    ports:
      # HTTP port for the WebUI.
      - 5050:5050
    restart: unless-stopped
