# [Budge](https://github.com/linuxserver/budge) is an open source 'budgeting
# with envelopes' personal finance app.

---
version: "2.1"
services:
  budge:
    image: ghcr.io/linuxserver/budge
    container_name: budge
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # specify a timezone to use, see this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
      - TZ=${TZ:-Europe/Amsterdam}
    volumes:
      # Persistent config files
      - ${BASEDIR:-/volume1/docker}/budge/config:/config
    ports:
      # http gui
      - 80:80
      # https gui
      - 443:443
    restart: unless-stopped
