# [Budge](https://github.com/linuxserver/budge) is an open source 'budgeting
# with envelopes' personal finance app.

---
version: "2.1"
services:
  budge:
    image: ghcr.io/linuxserver/budge
    container_name: budge
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Persistent config files
      - ${BASEDIR:-/volume1/docker}/budge/config:/config
    ports:
      # http gui
      - 80:80
      # https gui
      - 443:443
    restart: unless-stopped
