# [Emby](https://emby.media/) organizes video, music, live TV, and photos from
# personal media libraries and streams them to smart TVs, streaming boxes and
# mobile devices. This container is packaged as a standalone emby Media Server.

---

services:
  emby:
    image: ghcr.io/linuxserver/emby
    container_name: emby
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/emby:/config
      - ${DOCKERSTORAGEDIR:-/volume1/data}/media:/mnt/data/media
      # Path for Raspberry Pi OpenMAX libs *optional*.
      # - /opt/vc/lib:/opt/vc/lib
    # ports:
      # Http webUI.
      # - 8096:8096
      # Https webUI (you need to setup your own certificate). 
      # - 8920:8920 # optional
    networks:
      default:
        aliases:
          - emby
    devices:
      # Only needed if you want to use your Intel or AMD GPU for hardware accelerated video encoding (vaapi).
      # - /dev/dri:/dev/dri # optional
      # Only needed if you want to use your Raspberry Pi OpenMax video encoding (Bellagio).
      # - /dev/vchiq:/dev/vchiq # optional
      # Only needed if you want to use your Raspberry Pi V4L2 video encoding.
      # - /dev/video10:/dev/video10 # optional
      # Only needed if you want to use your Raspberry Pi V4L2 video encoding.
      # - /dev/video11:/dev/video11 # optional
      # Only needed if you want to use your Raspberry Pi V4L2 video encoding.
      # - /dev/video12:/dev/video12 # optional
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true