# [Manyfold](https://github.com/manyfold3d/manyfold/) is an open source, self-
# hosted web application for managing a collection of 3D models, particularly
# focused on 3D printing.

---

services:
  manyfold:
    image: ghcr.io/linuxserver/manyfold
    container_name: manyfold
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - DATABASE_URL=
      - REDIS_URL=
      - SECRET_KEY_BASE=
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/manyfold:/config
      # Location of your 3D model libraries.
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/manyfold/libraries:/libraries
    # ports:
      # Port for web frontend
      # - 3214:3214
    networks:
      default:
        aliases:
          - manyfold
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}