# [Lollypop](https://wiki.gnome.org/Apps/Lollypop) is a lightweight modern music
# player designed to work excellently on the GNOME desktop environment.

---
version: "2.1"
services:
  lollypop:
    image: ghcr.io/linuxserver/lollypop
    container_name: lollypop
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Users home directory in the container, stores settings and downloaded metadata for music.
      - ${BASEDIR:-/volume1/docker}/lollypop/config:/config
    ports:
      # Lollypop desktop gui.
      - 3000:3000
      # Lollypop desktop gui HTTPS.
      - 3001:3001
    restart: unless-stopped
