
# [Snipe-it](https://github.com/snipe/snipe-it) makes asset management easy. It
# was built by people solving real-world IT and asset management problems, and a
# solid UX has always been a top priority. Straightforward design and bulk
# actions mean getting things done faster.

---

services:
  snipe-it:
    image: ghcr.io/linuxserver/snipe-it
    container_name: snipe-it
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - APP_KEY=
      - APP_URL=http://localhost:8080
      - MYSQL_PORT_3306_TCP_ADDR=
      - MYSQL_PORT_3306_TCP_PORT=
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      # - APP_DEBUG=false # optional
      # - APP_ENV=production # optional
      # - APP_FORCE_TLS=false # optional
      # - APP_LOCALE= # optional
      # - MAIL_PORT_587_TCP_ADDR= # optional
      # - MAIL_PORT_587_TCP_PORT= # optional
      # - MAIL_ENV_FROM_ADDR= # optional
      # - MAIL_ENV_FROM_NAME= # optional
      # - MAIL_ENV_ENCRYPTION= # optional
      # - MAIL_ENV_USERNAME= # optional
      # - MAIL_ENV_PASSWORD= # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/snipe-it:/config
    # ports:
      # - 8080:80 # Snipe-IT Web UI
    networks:
      default:
        aliases:
          - snipe-it
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true