# [Ombi](https://ombi.io) allows you to host your own Plex Request and user
# management system. If you are sharing your Plex server with other users, allow
# them to request new content using an easy to manage interface! Manage all your
# requests for Movies and TV with ease, leave notes for the user and get
# notification when a user requests something. Allow your users to post issues
# against their requests so you know there is a problem with the audio etc. Even
# automatically send them weekly newsletters of new content that has been added
# to your Plex server!

---

services:
  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - BASE_URL=/ # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/ombi${DOCKERCONFIGDIR:-}:/config
    # ports:
      # web gui
      # - 3579:3579
    networks:
      default:
        aliases:
          - ombi
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
#    external: true
