# [Nzbget](http://nzbget.com/) is a usenet downloader, written in C++ and
# designed with performance in mind to achieve maximum download speed by using
# very little system resources.

---
version: "2.1"
services:
  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
      # Specify the user for web authentication.
      - NZBGET_USER=nzbget # optional
      # Specify the password for web authentication.
      - NZBGET_PASS=tegbzn6789 # optional
    volumes:
      # Persistent config
      - ${BASEDIR:-/volume1/docker}/nzbget/config:/config
      # Location of downloads on disk.
      - ${BASEDIR:-/volume1/docker}/nzbget/downloads:/downloads # optional
    ports:
      # WebUI
      - 6789:6789
    restart: unless-stopped
