# [Mylar3](https://github.com/mylar3/mylar3) is an automated Comic Book
# downloader (cbr/cbz) for use with NZB and torrents written in python. It
# supports SABnzbd, NZBGET, and many torrent clients in addition to DDL.

---

services:
  mylar3:
    image: ghcr.io/linuxserver/mylar3
    container_name: mylar3
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/mylar3${DOCKERCONFIGDIR:-}:/config
      # Map to your comics folder.
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/mylar3/comics:/comics
      - ${DOCKERSTORAGEPATH:-/volume1/data}/downloads:${DOCKERMOUNTPATH:-/mnt/data}/downloads
    # ports:
      # WebUI
      # - 8090:8090
    networks:
      default:
        aliases:
          - mylar3
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}