# [Apprise-api](https://github.com/caronc/apprise-api) Takes advantage of
# [Apprise](https://github.com/caronc/apprise) through your network with a user-
# friendly API. * Send notifications to more than 100 services. * An incredibly
# lightweight gateway to Apprise. * A production ready micro-service at your
# disposal. * A Simple Website to verify and test your configuration with.
# Apprise API was designed to easily fit into existing (and new) eco-systems
# that are looking for a simple notification solution.

---

services:
  apprise-api:
    image: ghcr.io/linuxserver/apprise-api
    container_name: apprise-api
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - APPRISE_ATTACH_SIZE=0 # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/apprise-api:/config
      # Temporary storage for attachments when sent with notifications.
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/apprise-api/attachments:/attachments
    # ports:
      # Port for apprise's interface and API.
      # - 8000:8000
    networks:
      default:
        aliases:
          - apprise-api
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true