# [Duplicati](https://www.duplicati.com/) is a backup client that securely
# stores encrypted, incremental, compressed backups on local storage, cloud
# storage services and remote file servers. It works with standard protocols
# like FTP, SSH, WebDAV as well as popular services like Microsoft OneDrive,
# Amazon S3, Google Drive, box.com, Mega, B2, and many others.

---

services:
  duplicati:
    image: ghcr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - SETTINGS_ENCRYPTION_KEY=
      # - CLI_ARGS= # optional
      # - DUPLICATI__WEBSERVICE_PASSWORD= # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/duplicati${DOCKERCONFIGDIR:-}:/config
      # Path to store local backups.
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/duplicati/backups:/backups
      # Path to source for files to backup.
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/duplicati/source:/source
    # ports:
      # http gui
      # - 8200:8200
    networks:
      default:
        aliases:
          - duplicati
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}