# [Tautulli](http://tautulli.com) is a python based web application for
# monitoring, analytics and notifications for Plex Media Server.

---

services:
  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/tautulli${DOCKERCONFIGDIR:-}:/config
      # Plex logs
      # - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/plex/Library/Application Support/Plex Media Server/Logs:/plex_logs
    # ports:
      # WebUI
      # - 8181:8181
    networks:
      default:
        aliases:
          - tautulli
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}