
# [Tautulli](http://tautulli.com) is a python based web application for
# monitoring, analytics and notifications for Plex Media Server.

---

services:
  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/tautulli:/config
      # - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/plex/Library/Application Support/Plex Media Server/Logs:/plex_logs # Plex logs
    # ports:
      # - 8181:8181 # WebUI
    networks:
      default:
        aliases:
          - tautulli
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true