# [Doplarr](https://github.com/kiranshila/Doplarr) is an *arr request bot for
# Discord.'

---

services:
  doplarr:
    image: ghcr.io/linuxserver/doplarr
    container_name: doplarr
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - DISCORD__TOKEN=
      - OVERSEERR__API=
      - OVERSEERR__URL=http://localhost:5055
      - RADARR__API=
      - RADARR__URL=http://localhost:7878
      - SONARR__API=
      - SONARR__URL=http://localhost:8989
      # - DISCORD__MAX_RESULTS=25 # optional
      # - DISCORD__REQUESTED_MSG_STYLE=:plain # optional
      # - SONARR__QUALITY_PROFILE= # optional
      # - RADARR__QUALITY_PROFILE= # optional
      # - SONARR__ROOTFOLDER= # optional
      # - RADARR__ROOTFOLDER= # optional
      # - SONARR__LANGUAGE_PROFILE= # optional
      # - OVERSEERR__DEFAULT_ID= # optional
      # - PARTIAL_SEASONS=true # optional
      # - LOG_LEVEL=:info # optional
      # - JAVA_OPTS= # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/doplarr${DOCKERCONFIGDIR:-}:/config
    # ports:
      # # Application WebUI
      # - 80:80
    networks:
      default:
        aliases:
          - doplarr
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: ${NETWORK_EXTERNAL:-false}
