# [Ungoogled Chromium](https://github.com/ungoogled-software/ungoogled-chromium)
# is Google Chromium, sans dependency on Google web services.

---
version: "2.1"
services:
  ungoogled-chromium:
    image: ghcr.io/linuxserver/ungoogled-chromium
    container_name: ungoogled-chromium
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # specify a timezone to use, see this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
      - TZ=${TZ:-Europe/Amsterdam}
      # Specify one or multiple Chromium CLI flags, this string will be passed to the application in full.
      - CHROME_CLI=https://www.linuxserver.io/ # optional
    volumes:
      # Users home directory in the container, stores local files and settings
      - ${BASEDIR:-/volume1/docker}/ungoogled-chromium/config:/config
    ports:
      # Ungoogled Chromium desktop gui.
      - 3000:3000
      # HTTPS Ungoogled Chromium desktop gui.
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped
