# [Tvheadend](https://www.tvheadend.org/) works as a proxy server: is a TV
# streaming server and recorder for Linux, FreeBSD and Android supporting DVB-S,
# DVB-S2, DVB-C, DVB-T, ATSC, ISDB-T, IPTV, SAT>IP and HDHomeRun as input
# sources. Tvheadend offers the HTTP (VLC, MPlayer), HTSP (Kodi, Movian) and
# SAT>IP streaming. Multiple EPG sources are supported (over-the-air DVB and
# ATSC including OpenTV DVB extensions, XMLTV, PyXML).

---

services:
  tvheadend:
    image: ghcr.io/linuxserver/tvheadend
    container_name: tvheadend
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - RUN_OPTS= # optional
    volumes:
      ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/tvheadend:/config
      # Where you want the PVR to store recordings.
      ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/tvheadend/recordings:/recordings
    # ports:
      # WebUI
      # - 9981:9981
      # HTSP server port.
      # - 9982:9982
    networks:
      default:
        aliases:
          - tvheadend
    devices:
      # Only needed if you want to use your AMD/Intel GPU for hardware accelerated video encoding (vaapi).
      # - /dev/dri:/dev/dri # optional
      # Only needed if you want to pass through a DVB card to the container. If you use IPTV or HDHomeRun you can leave it out.
      # - /dev/dvb:/dev/dvb # optional
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true