# [Freshrss](https://freshrss.org/) is a free, self-hostable aggregator for rss
# feeds.

---

services:
  freshrss:
    image: ghcr.io/linuxserver/freshrss
    container_name: freshrss
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/freshrss${DOCKERCONFIGDIR:-}:/config
    # ports:
      # WebUI
      # - 80:80
    networks:
      default:
        aliases:
          - freshrss
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}