
# [Obsidian](https://obsidian.md) is a note-taking app that lets you create,
# link, and organize your notes on your device, with hundreds of plugins and
# themes to customize your workflow. You can also publish your notes online,
# access them offline, and sync them securely with end-to-end encryption.

---

services:
  obsidian:
    image: ghcr.io/linuxserver/obsidian
    container_name: obsidian
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/obsidian:/config
    # ports:
      # - 3000:3000 # Obsidian desktop gui.
      # - 3001:3001 # Obsidian desktop gui HTTPS.
    networks:
      default:
        aliases:
          - obsidian
    devices:
      # Add this for GL support (Linux hosts only)
      - /dev/dri:/dev/dri # optional
    shm_size: "1gb"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true