
# [FIleZilla](https://filezilla-project.org/) Client is a fast and reliable
# cross-platform FTP, FTPS and SFTP client with lots of useful features and an
# intuitive graphical user interface.

---

services:
  filezilla:
    image: ghcr.io/linuxserver/filezilla
    container_name: filezilla
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/filezilla:/config
    # ports:
      # - 3000:3000 # FileZilla desktop gui.
      # - 3001:3001 # FileZilla desktop gui HTTPS.
    networks:
      default:
        aliases:
          - filezilla
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true