
# This container needs special attention. Please check https://hub.docker.com/r/linuxserver/socket-proxy for details.
---

services:
  socket-proxy:
    image: ghcr.io/linuxserver/socket-proxy
    container_name: socket-proxy
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/socket-proxy:/config
    # ports:
    networks:
      default:
        aliases:
          - socket-proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true