# This container needs special attention. Please check https://hub.docker.com/r/linuxserver/yq for details.
---
version: "2.1"
services:
  yq:
    image: ghcr.io/linuxserver/yq
    container_name: yq
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Configuration files.
      - ${BASEDIR:-/volume1/docker}/yq/config:/config
    ports:
    restart: unless-stopped
