
# [Fleet](https://github.com/linuxserver/fleet) provides an online web interface
# which displays a set of maintained images from one or more owned repositories.

---

services:
  fleet:
    image: ghcr.io/linuxserver/fleet
    container_name: fleet
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - fleet_admin_authentication_type=DATABASE
      - fleet_database_url=jdbc:mariadb://<url>:3306/fleet
      - fleet_database_username=fleet_user
      - fleet_database_password=dbuserpassword
      # - fleet_admin_secret=randomstring # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/fleet:/config
    # ports:
      # - 8080:8080 # Http port
    networks:
      default:
        aliases:
          - fleet
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true