# [Shotcut](https://www.shotcut.org/) is a free, open source, cross-platform
# video editor.

---

services:
  shotcut:
    image: ghcr.io/linuxserver/shotcut
    container_name: shotcut
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/shotcut:/config
    # ports:
      # Shotcut desktop gui.
      # - 3000:3000
      # Shotcut desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - shotcut
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true