# [Audacity](https://www.audacityteam.org/) is an easy-to-use, multi-track audio
# editor and recorder. Developed by a group of volunteers as open source.

---

services:
  audacity:
    image: ghcr.io/linuxserver/audacity
    container_name: audacity
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/audacity${DOCKERCONFIGDIR:-}:/config
    # ports:
      # # Audacity desktop gui.
      # - 3000:3000
      # # Audacity desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - audacity
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: ${NETWORK_EXTERNAL:-false}
