
# [Audacity](https://www.audacityteam.org/) is an easy-to-use, multi-track audio
# editor and recorder. Developed by a group of volunteers as open source.

---

services:
  audacity:
    image: ghcr.io/linuxserver/audacity
    container_name: audacity
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/audacity:/config
    # ports:
      # - 3000:3000 # Audacity desktop gui.
      # - 3001:3001 # Audacity desktop gui HTTPS.
    networks:
      default:
        aliases:
          - audacity
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true