
# [Projectsend](http://www.projectsend.org) is a self-hosted application that
# lets you upload files and assign them to specific clients that you create
# yourself. Secure, private and easy. No more depending on external services or
# e-mail to send those files.

---

services:
  projectsend:
    image: ghcr.io/linuxserver/projectsend
    container_name: projectsend
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/projectsend:/config
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/projectsend/data:/data
    # ports:
      # - 80:80 # WebUI
    networks:
      default:
        aliases:
          - projectsend
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true