# [QDirStat](https://github.com/shundhammer/qdirstat) Qt-based directory
# statistics: KDirStat without any KDE -- from the author of the original
# KDirStat.

---

services:
  qdirstat:
    image: ghcr.io/linuxserver/qdirstat
    container_name: qdirstat
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/qdirstat${DOCKERCONFIGDIR:-}:/config
      - ${DOCKERSTORAGEPATH:-/volume1/data}:${DOCKERMOUNTPATH:-/mnt/data}
    # ports:
      # # QdirStat desktop gui.
      # - 3000:3000
      # # QdirStat desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - qdirstat
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
