
# [QDirStat](https://github.com/shundhammer/qdirstat) Qt-based directory
# statistics: KDirStat without any KDE -- from the author of the original
# KDirStat.

---

services:
  qdirstat:
    image: ghcr.io/linuxserver/qdirstat
    container_name: qdirstat
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/qdirstat:/config
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/qdirstat/data:/data
    # ports:
      # - 3000:3000 # QdirStat desktop gui.
      # - 3001:3001 # QdirStat desktop gui HTTPS.
    networks:
      default:
        aliases:
          - qdirstat
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true