# [Kometa](https://github.com/Kometa-Team/Kometa) is a powerful tool designed to
# give you complete control over your media libraries. With Kometa, you can take
# your customization to the next level, with granular control over metadata,
# collections, overlays, and much more.

---

services:
  kometa:
    image: ghcr.io/linuxserver/kometa
    container_name: kometa
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - KOMETA_CONFIG=/config/config.yml # optional
      # - KOMETA_TIME=03:00 # optional
      # - KOMETA_RUN=False # optional
      # - KOMETA_TEST=False # optional
      # - KOMETA_NO_MISSING=False # optional
    volumes:
      ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/kometa:/config
    # ports:
      # Application WebUI
      # - 80:80
    networks:
      default:
        aliases:
          - kometa
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true