# [Htpcmanager](https://github.com/HTPC-Manager/HTPC-Manager) is a front end for
# many htpc related applications.

---
version: "2.1"
services:
  htpcmanager:
    image: ghcr.io/linuxserver/htpcmanager
    container_name: htpcmanager
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # specify a timezone to use, see this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
      - TZ=${TZ:-Europe/Amsterdam}
    volumes:
      # Persistent config files
      - ${BASEDIR:-/volume1/docker}/htpcmanager/config:/config
    ports:
      # Application WebUI
      - 8085:8085
    restart: unless-stopped
