# [Thelounge](https://thelounge.github.io/) (a fork of shoutIRC) is a web IRC
# client that you host on your own server.

---

services:
  thelounge:
    image: ghcr.io/linuxserver/thelounge
    container_name: thelounge
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/thelounge${DOCKERCONFIGDIR:-}:/config
    # ports:
      # Application WebUI
      # - 9000:9000
    networks:
      default:
        aliases:
          - thelounge
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}