# [Inkscape](https://inkscape.org/) is professional quality vector graphics
# software which runs on Linux, Mac OS X and Windows desktop computers.

---

services:
  inkscape:
    image: ghcr.io/linuxserver/inkscape
    container_name: inkscape
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/inkscape:/config
    # ports:
      # Inkscape desktop gui.
      # - 3000:3000
      # Inkscape desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - inkscape
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}