
# [FreeTube](https://freetubeapp.io/) is a feature-rich and user-friendly
# YouTube client with a focus on privacy.

---

services:
  freetube:
    image: ghcr.io/linuxserver/freetube
    container_name: freetube
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/freetube:/config
    # ports:
      # - 3000:3000 # FreeTube desktop gui.
      # - 3001:3001 # HTTPS FreeTube desktop gui.
    networks:
      default:
        aliases:
          - freetube
    shm_size: "1gb"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true