# [Raneto](http://raneto.com/) - is an open source Knowledgebase platform that
# uses static Markdown files to power your Knowledgebase.

---

services:
  raneto:
    image: ghcr.io/linuxserver/raneto
    container_name: raneto
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/raneto${DOCKERCONFIGDIR:-}:/config
    # ports:
      # The port for the Raneto web interface
      # - 3000:3000
    networks:
      default:
        aliases:
          - raneto
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}