# [digiKam](https://www.digikam.org/): Professional Photo Management with the
# Power of Open Source

---
version: "2.1"
services:
  digikam:
    image: ghcr.io/linuxserver/digikam
    container_name: digikam
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
      # Specify a subfolder to use with reverse proxies, IE `/subfolder/`
      - SUBFOLDER=/ # optional
    volumes:
      # Users home directory in the container, stores database.
      - ${BASEDIR:-/volume1/docker}/digikam/config:/config
    ports:
      # digiKam desktop gui
      - 3000:3000 # optional
      # digiKam desktop gui HTTPS
      - 3001:3001 # optional
    restart: unless-stopped
