# [digiKam](https://www.digikam.org/): Professional Photo Management with the
# Power of Open Source

---
version: "2.1"
services:
  digikam:
    image: ghcr.io/linuxserver/digikam
    container_name: digikam
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # specify a timezone to use, see this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
      - TZ=${TZ:-Europe/Amsterdam}
      # Specify a subfolder to use with reverse proxies, IE `/subfolder/`
      - SUBFOLDER=/ # optional
    volumes:
      # Users home directory in the container, stores database.
      - ${BASEDIR:-/volume1/docker}/digikam/config:/config
    ports:
      # digiKam desktop gui
      - 3000:3000 # optional
      # digiKam desktop gui HTTPS
      - 3001:3001 # optional
    restart: unless-stopped
