# [Openssh-server](https://www.openssh.com/) is a sandboxed environment that
# allows ssh access without giving keys to the entire server. Giving ssh access
# via private key often means giving full access to the server. This container
# creates a limited and sandboxed environment that others can ssh into. The
# users only have access to the folders mapped and the processes running inside
# this container.

---

services:
  openssh-server:
    image: ghcr.io/linuxserver/openssh-server
    container_name: openssh-server
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - PUBLIC_KEY=yourpublickey # optional
      # - PUBLIC_KEY_FILE=/path/to/file # optional
      # - PUBLIC_KEY_DIR=/path/to/directory/containing/_only_/pubkeys # optional
      # - PUBLIC_KEY_URL=https://github.com/username.keys # optional
      # - SUDO_ACCESS=false # optional
      # - PASSWORD_ACCESS=false # optional
      # - USER_PASSWORD=password # optional
      # - USER_PASSWORD_FILE=/path/to/file # optional
      # - USER_NAME=linuxserver.io # optional
      # - LOG_STDOUT= # optional
    volumes:
      ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/openssh-server:/config
    # ports:
      # ssh port
      # - 2222:2222
    networks:
      default:
        aliases:
          - openssh-server
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true