# [Pydio-cells](https://pydio.com/) is the nextgen file sharing platform for
# organizations. It is a full rewrite of the Pydio project using the Go language
# following a micro-service architecture.

---

services:
  pydio-cells:
    image: ghcr.io/linuxserver/pydio-cells
    container_name: pydio-cells
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - EXTERNALURL=yourdomain.url
      # - SERVER_IP=0.0.0.0 # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/pydio-cells${DOCKERCONFIGDIR:-}:/config
    # ports:
      # Http port
      # - 8080:8080
    networks:
      default:
        aliases:
          - pydio-cells
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}