# [Kimai](https://kimai.org/) is a professional grade time-tracking application,
# free and open-source. It handles use-cases of freelancers as well as companies
# with dozens or hundreds of users. Kimai was build to track your project times
# and ships with many advanced features, including but not limited to: JSON API,
# invoicing, data exports, multi-timer and punch-in punch-out mode, tagging,
# multi-user - multi-timezones - multi-language ([over 30 translations
# existing](https://hosted.weblate.org/projects/kimai/)!), authentication via
# SAML/LDAP/Database, two-factor authentication (2FA) with TOTP, customizable
# role and team permissions, responsive design, user/customer/project specific
# rates, advanced search & filtering, money and time budgets, advanced
# reporting, support for [plugins](https://www.kimai.org/store/) and so much
# more.

---

services:
  kimai:
    image: ghcr.io/linuxserver/kimai
    container_name: kimai
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - DATABASE_URL=mysql://your_db_user:your_db_pass@your_db_host:3306/your_db_name?charset=your_db_charset&serverVersion=your_db_version
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/kimai${DOCKERCONFIGDIR:-}:/config
    # ports:
      # # http gui
      # - 80:80
      # # https gui
      # - 443:443
    networks:
      default:
        aliases:
          - kimai
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
