# The [Unifi-network-application](https://ui.com/) software is a powerful,
# enterprise wireless software engine ideal for high-density client deployments
# requiring low latency and high uptime performance.

---

services:
  unifi-network-application:
    image: ghcr.io/linuxserver/unifi-network-application
    container_name: unifi-network-application
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - MONGO_USER=unifi
      - MONGO_PASS=
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
      # - MEM_LIMIT=1024 # optional
      # - MEM_STARTUP=1024 # optional
      # - MONGO_TLS= # optional
    volumes:
      ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/unifi-network-application:/config
    # ports:
      # Unifi web admin port
      # - 8443:8443
      # Unifi STUN port
      # - 3478:3478/udp
      # Required for AP discovery
      # - 10001:10001/udp
      # Required for device communication
      # - 8080:8080
      # Required for `Make controller discoverable on L2 network` option 
      # - 1900:1900/udp # optional
      # Unifi guest portal HTTPS redirect port 
      # - 8843:8843 # optional
      # Unifi guest portal HTTP redirect port 
      # - 8880:8880 # optional
      # For mobile throughput test 
      # - 6789:6789 # optional
      # Remote syslog port 
      # - 5514:5514/udp # optional
    networks:
      default:
        aliases:
          - unifi-network-application
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true