# SWAG - Secure Web Application Gateway (formerly known as letsencrypt, no
# relation to Let's Encrypt™) sets up an Nginx webserver and reverse proxy with
# php support and a built-in certbot client that automates free SSL server
# certificate generation and renewal processes (Let's Encrypt and ZeroSSL). It
# also contains fail2ban for intrusion prevention.

---

services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - URL=example.com
      - VALIDATION=http
      # - SUBDOMAINS=www, # optional
      # - CERTPROVIDER= # optional
      # - DNSPLUGIN=cloudflare # optional
      # - PROPAGATION= # optional
      # - EMAIL= # optional
      # - ONLY_SUBDOMAINS=false # optional
      # - EXTRA_DOMAINS= # optional
      # - STAGING=false # optional
      # - DISABLE_F2B= # optional
      # - SWAG_AUTORELOAD= # optional
      # - SWAG_AUTORELOAD_WATCHLIST= # optional
    volumes:
      ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/swag:/config
    # ports:
      # HTTPS port
      # - 443:443
      # HTTP port (required for HTTP validation and HTTP -> HTTPS redirect) 
      # - 80:80 # optional
    networks:
      default:
        aliases:
          - swag
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true