# [Krita](https://krita.org/en/) is a professional FREE and open source painting
# program. It is made by artists that want to see affordable art tools for
# everyone.

---

services:
  krita:
    image: ghcr.io/linuxserver/krita
    container_name: krita
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/krita:/config
    # ports:
      # Krita desktop gui.
      # - 3000:3000
      # Krita desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - krita
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}