# This container needs special attention. Please check https://hub.docker.com/r/linuxserver/qemu-static for details.
---

services:
  qemu-static:
    image: ghcr.io/linuxserver/qemu-static
    container_name: qemu-static
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/qemu-static:/config
    # ports:
    networks:
      default:
        aliases:
          - qemu-static
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true