# [Spotube](https://spotube.krtirtho.dev/) is an open source, cross-platform
# Spotify client compatible across multiple platforms utilizing Spotify's data
# API and YouTube, Piped.video or JioSaavn as an audio source, eliminating the
# need for Spotify Premium

---
version: "2.1"
services:
  spotube:
    image: ghcr.io/linuxserver/spotube
    container_name: spotube
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Users home directory in the container, stores local files and settings
      - ${BASEDIR:-/volume1/docker}/spotube/config:/config
    ports:
      # Spotube desktop gui.
      - 3000:3000
      # HTTPS Spotube desktop gui.
      - 3001:3001
    restart: unless-stopped
