# [Pylon](https://github.com/pylonide/pylon) is a web based integrated
# development environment built with Node.js as a backend and with a
# supercharged JavaScript/HTML5 frontend, licensed under GPL version 3. This
# project originates from Cloud9 v2 project.

---

services:
  pylon:
    image: ghcr.io/linuxserver/pylon
    container_name: pylon
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - GITURL=https://github.com/linuxserver/docker-pylon.git # optional
      # - PYUSER=myuser # optional
      # - PYPASS=mypass # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/pylon${DOCKERCONFIGDIR:-}:/config
      # Optionally if you want the bind mount your own code and have changes survive container upgrades.
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/pylon/code:/code
    # ports:
      # # The port for the Pylon web interface
      # - 3131:3131
    networks:
      default:
        aliases:
          - pylon
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
