# [Webtop](https://github.com/linuxserver/docker-webtop) - Alpine, Ubuntu,
# Fedora, and Arch based containers containing full desktop environments in
# officially supported flavors accessible via any modern web browser.

---

services:
  webtop:
    image: ghcr.io/linuxserver/webtop
    container_name: webtop
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - SUBFOLDER=/ # optional
      # - TITLE=Webtop # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/webtop${DOCKERCONFIGDIR:-}:/config
      # Docker Socket on the system, if you want to use Docker in the container
      - /var/run/docker.sock:/var/run/docker.sock
    # ports:
      # Web Desktop GUI
      # - 3000:3000
      # Web Desktop GUI HTTPS
      # - 3001:3001
    networks:
      default:
        aliases:
          - webtop
    devices:
      # Add this for GL support (Linux hosts only)
      # - /dev/dri:/dev/dri # optional
    # shm_size: "1gb" # optional
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
#    external: true
