
# [Double Commander](https://doublecmd.sourceforge.io/) is a free cross platform
# open source file manager with two panels side by side. It is inspired by Total
# Commander and features some new ideas.

---

services:
  doublecommander:
    image: ghcr.io/linuxserver/doublecommander
    container_name: doublecommander
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/doublecommander:/config
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/doublecommander/data:/data
    # ports:
      # - 3000:3000 # Double Commander desktop gui.
      # - 3001:3001 # Double Commander desktop gui HTTPS.
    networks:
      default:
        aliases:
          - doublecommander
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true