# [Double Commander](https://doublecmd.sourceforge.io/) is a free cross platform
# open source file manager with two panels side by side. It is inspired by Total
# Commander and features some new ideas.

---

services:
  doublecommander:
    image: ghcr.io/linuxserver/doublecommander
    container_name: doublecommander
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/doublecommander${DOCKERCONFIGDIR:-}:/config
      - ${DOCKERSTORAGEPATH:-/volume1/data}:${DOCKERMOUNTPATH:-/mnt/data}
    # ports:
      # # Double Commander desktop gui.
      # - 3000:3000
      # # Double Commander desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - doublecommander
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: ${NETWORK_EXTERNAL:-false}
