
# [Resilio-sync](https://www.resilio.com/individuals/) (formerly BitTorrent
# Sync) uses the BitTorrent protocol to sync files and folders between all of
# your devices. There are both free and paid versions, this container supports
# both. There is an official sync image but we created this one as it supports
# user mapping to simplify permissions for volumes.

---

services:
  resilio-sync:
    image: ghcr.io/linuxserver/resilio-sync
    container_name: resilio-sync
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/resilio-sync:/config
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/resilio-sync/sync:/sync
      - ${DOCKERSTORAGEDIR:-/volume1/data}/downloads:/mnt/data/downloads
    # ports:
      # - 8888:8888 # WebUI
      # - 55555:55555 # Sync Port.
    networks:
      default:
        aliases:
          - resilio-sync
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true