# [Plex](https://plex.tv) organizes video, music and photos from personal media
# libraries and streams them to smart TVs, streaming boxes and mobile devices.
# This container is packaged as a standalone Plex Media Server. Straightforward
# design and bulk actions mean getting things done faster.

---

services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    # network_mode: host
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - VERSION=docker
      # - PLEX_CLAIM= # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/plex:/config
      - ${DOCKERSTORAGEDIR:-/volume1/data}/media:/mnt/data/media
    ports:
      # Plex Media Server
      - 32400:32400/tcp
      # GDM network discovery (local)
      # - 32412:32412/udp
      # GDM network discovery (local)
      # - 32410:32410/udp
      # GDM network discovery (local)
      # - 32413:32413/udp
      # GDM network discovery (local)
      # - 32414:32414/udp
    networks:
      default:
        aliases:
          - plex
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}