
# [Librespeed](https://github.com/librespeed/speedtest) is a very lightweight
# Speedtest implemented in Javascript, using XMLHttpRequest and Web Workers. No
# Flash, No Java, No Websocket, No Bullshit.

---

services:
  librespeed:
    image: ghcr.io/linuxserver/librespeed
    container_name: librespeed
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - PASSWORD=PASSWORD
      # - CUSTOM_RESULTS=false # optional
      # - DB_TYPE=sqlite # optional
      # - DB_NAME=DB_NAME # optional
      # - DB_HOSTNAME=DB_HOSTNAME # optional
      # - DB_USERNAME=DB_USERNAME # optional
      # - DB_PASSWORD=DB_PASSWORD # optional
      # - DB_PORT=DB_PORT # optional
      # - IPINFO_APIKEY=ACCESS_TOKEN # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/librespeed:/config
    # ports:
      # - 80:80 # web gui
    networks:
      default:
        aliases:
          - librespeed
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true