# [Speedtest-tracker](https://github.com/alexjustesen/speedtest-tracker) is a
# self-hosted internet performance tracking application that runs speedtest
# checks against Ookla's Speedtest service.

---
version: "2.1"
services:
  speedtest-tracker:
    image: ghcr.io/linuxserver/speedtest-tracker
    container_name: speedtest-tracker
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
      # App key used for encrypting stored data. You can generate a key at [https://speedtest-tracker.dev](https://speedtest-tracker.dev)
      - APP_KEY=
      # The IP:port or URL your application will be accessed on (ie. `http://192.168.1.1:6875` or `https://bookstack.mydomain.com`
      - APP_URL=
      # Set the database type to use. `sqlite`, `pgsql`, or `mysql`
      - DB_CONNECTION=sqlite
      # Set the test schedule in cron format. e.g. `0 */6 * * *`
      - SPEEDTEST_SCHEDULE=
      # A comma-separated list of server IDs to test against. Run `docker run -it --rm --entrypoint /bin/bash lscr.io/linuxserver/speedtest-tracker:latest list-servers` to get a list of nearby servers.
      - SPEEDTEST_SERVERS=
      # Database hostname (postgres/mysql).
      - DB_HOST= # optional
      # Database port (postgres/mysql).
      - DB_PORT= # optional
      # Database name (postgres/mysql).
      - DB_DATABASE= # optional
      # Database username (postgres/mysql).
      - DB_USERNAME= # optional
      # Database password (postgres/mysql).
      - DB_PASSWORD= # optional
      # Timezone for the UI.
      - DISPLAY_TIMEZONE=Etc/UTC # optional
      # Days to keep test results.
      - PRUNE_RESULTS_OLDER_THAN=0 # optional
    volumes:
      # Contains speedtest-tracker config and database, if using sqlite.
      - ${BASEDIR:-/volume1/docker}/speedtest-tracker/config:/config
    ports:
      # Web UI
      - 80:80
    restart: unless-stopped
