# [Adguardhome-sync](https://github.com/bakito/adguardhome-sync/) is a tool to
# synchronize AdGuardHome config to replica instances.

---

services:
  adguardhome-sync:
    image: ghcr.io/linuxserver/adguardhome-sync
    container_name: adguardhome-sync
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - CONFIGFILE=/config/adguardhome-sync.yaml # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/adguardhome-sync${DOCKERCONFIGDIR:-}:/config
    # ports:
      # # Port for AdGuardHome Sync's web API.
      # - 8080:8080
    networks:
      default:
        aliases:
          - adguardhome-sync
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: ${NETWORK_EXTERNAL:-false}
