# This container needs special attention. Please check https://hub.docker.com/r/linuxserver/ffmpeg for details.
---
version: "2.1"
services:
  ffmpeg:
    image: ghcr.io/linuxserver/ffmpeg
    container_name: ffmpeg
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Configuration files.
      - ${BASEDIR:-/volume1/docker}/ffmpeg/config:/config
    ports:
      # Application WebUI
      - 80:80
    restart: unless-stopped
