# [OpenShot](https://openshot.org/) Video Editor is an award-winning free and
# open-source video editor for Linux, Mac, and Windows, and is dedicated to
# delivering high quality video editing and animation solutions to the world.

---

services:
  openshot:
    image: ghcr.io/linuxserver/openshot
    container_name: openshot
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/openshot${DOCKERCONFIGDIR:-}:/config
    # ports:
      # OpenShot desktop gui.
      # - 3000:3000
      # OpenShot desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - openshot
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}