# [KiCad](https://www.kicad.org/) - A Cross Platform and Open Source Electronics
# Design Automation Suite.

---

services:
  kicad:
    image: ghcr.io/linuxserver/kicad
    container_name: kicad
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/kicad${DOCKERCONFIGDIR:-}:/config
    # ports:
      # # KiCad desktop gui.
      # - 3000:3000
      # # KiCad desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - kicad
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
