
# [KiCad](https://www.kicad.org/) - A Cross Platform and Open Source Electronics
# Design Automation Suite.

---

services:
  kicad:
    image: ghcr.io/linuxserver/kicad
    container_name: kicad
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/kicad:/config
    # ports:
      # - 3000:3000 # KiCad desktop gui.
      # - 3001:3001 # KiCad desktop gui HTTPS.
    networks:
      default:
        aliases:
          - kicad
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true