# [Ldap-auth](https://github.com/nginxinc/nginx-ldap-auth) software is for
# authenticating users who request protected resources from servers proxied by
# nginx. It includes a daemon (ldap-auth) that communicates with an
# authentication server, and a webserver daemon that generates an authentication
# cookie based on the user’s credentials. The daemons are written in Python for
# use with a Lightweight Directory Access Protocol (LDAP) authentication server
# (OpenLDAP or Microsoft Windows Active Directory 2003 and 2012).

---

services:
  ldap-auth:
    image: ghcr.io/linuxserver/ldap-auth
    container_name: ldap-auth
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - FERNETKEY= # optional
      # - CERTFILE= # optional
      # - KEYFILE= # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/ldap-auth${DOCKERCONFIGDIR:-}:/config
    # ports:
      # # the port for ldap auth daemon
      # - 8888:8888
      # # the port for ldap login page
      # - 9000:9000
    networks:
      default:
        aliases:
          - ldap-auth
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
