# [SickGear](https://github.com/sickgear/sickgear) provides management of TV
# shows and/or Anime, it detects new episodes, links downloader apps, and more..
# For more information on SickGear visit their website and check it out:
# https://github.com/SickGear/SickGear

---
version: "2.1"
services:
  sickgear:
    image: ghcr.io/linuxserver/sickgear
    container_name: sickgear
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Persistent configuration files.
      - ${BASEDIR:-/volume1/docker}/sickgear/config:/config
      # where you store your tv shows
      - ${BASEDIR:-/volume1/docker}/sickgear/tv:/tv
      # your downloads folder for post processing (must not be download in progress)
      - ${BASEDIR:-/volume1/docker}/sickgear/downloads:/downloads
    ports:
      # will map the container's port 8081 to port 8081 on the host
      - 8081:8081
    restart: unless-stopped
