# [Freshrss](https://freshrss.org/) is a free, self-hostable aggregator for rss
# feeds.

---
version: "2.1"
services:
  freshrss:
    image: ghcr.io/linuxserver/freshrss
    container_name: freshrss
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Persistent config files
      - ${BASEDIR:-/volume1/docker}/freshrss/config:/config
    ports:
      # WebUI
      - 80:80
    restart: unless-stopped
