# [Piwigo](http://piwigo.org/) is a photo gallery software for the web that
# comes with powerful features to publish and manage your collection of
# pictures.

---
version: "2.1"
services:
  piwigo:
    image: ghcr.io/linuxserver/piwigo
    container_name: piwigo
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Persistent config files
      - ${BASEDIR:-/volume1/docker}/piwigo/config:/config
      # Image storage for Piwigo
      - ${BASEDIR:-/volume1/docker}/piwigo/gallery:/gallery
    ports:
      # Application WebUI
      - 80:80
    restart: unless-stopped
