
# [Chromium](https://www.chromium.org/chromium-projects/) is an open-source
# browser project that aims to build a safer, faster, and more stable way for
# all users to experience the web.

---

services:
  chromium:
    image: ghcr.io/linuxserver/chromium
    container_name: chromium
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - CHROME_CLI=https://www.linuxserver.io/ # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/chromium:/config
    # ports:
      # - 3000:3000 # Chromium desktop gui.
      # - 3001:3001 # HTTPS Chromium desktop gui.
    networks:
      default:
        aliases:
          - chromium
    shm_size: "1gb"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true