
# [Openvscode-server](https://github.com/gitpod-io/openvscode-server) provides a
# version of VS Code that runs a server on a remote machine and allows access
# through a modern web browser.

---

services:
  openvscode-server:
    image: ghcr.io/linuxserver/openvscode-server
    container_name: openvscode-server
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - CONNECTION_TOKEN= # optional
      # - CONNECTION_SECRET= # optional
      # - SUDO_PASSWORD=password # optional
      # - SUDO_PASSWORD_HASH= # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/openvscode-server:/config
    # ports:
      # - 3000:3000 # Web UI port.
    networks:
      default:
        aliases:
          - openvscode-server
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true