# [Orca Slicer](https://github.com/SoftFever/OrcaSlicer) is an open source
# slicer for FDM printers. OrcaSlicer is fork of Bambu Studio, it was previously
# known as BambuStudio-SoftFever, Bambu Studio is forked from PrusaSlicer by
# Prusa Research, which is from Slic3r by Alessandro Ranellucci and the RepRap
# community

---
version: "2.1"
services:
  orcaslicer:
    image: ghcr.io/linuxserver/orcaslicer
    container_name: orcaslicer
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Users home directory in the container, stores program settings and files.
      - ${BASEDIR:-/volume1/docker}/orcaslicer/config:/config
    ports:
      # Orca Slicer desktop gui.
      - 3000:3000
      # Orca Slicer desktop gui HTTPS.
      - 3001:3001
    restart: unless-stopped
