# [Thelounge](https://thelounge.github.io/) (a fork of shoutIRC) is a web IRC
# client that you host on your own server.

---
version: "2.1"
services:
  thelounge:
    image: ghcr.io/linuxserver/thelounge
    container_name: thelounge
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Persistent config files
      - ${BASEDIR:-/volume1/docker}/thelounge/config:/config
    ports:
      # Application WebUI
      - 9000:9000
    restart: unless-stopped
