# [Nzbget](http://nzbget.com/) is a usenet downloader, written in C++ and
# designed with performance in mind to achieve maximum download speed by using
# very little system resources.

---

services:
  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - NZBGET_USER=nzbget # optional
      # - NZBGET_PASS=tegbzn6789 # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/nzbget${DOCKERCONFIGDIR:-}:/config
      - ${DOCKERSTORAGEPATH:-/volume1/data}/downloads:${DOCKERMOUNTPATH:-/mnt/data}/downloads
    # ports:
      # WebUI
      # - 6789:6789
    networks:
      default:
        aliases:
          - nzbget
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}