# [Calibre-web](https://github.com/janeczku/calibre-web) is a web app providing
# a clean interface for browsing, reading and downloading eBooks using an
# existing Calibre database. It is also possible to integrate google drive and
# edit metadata and your calibre library through the app itself. This software
# is a fork of library and licensed under the GPL v3 License.

---

services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - DOCKER_MODS=linuxserver/mods:universal-calibre # optional
      # - OAUTHLIB_RELAX_TOKEN_SCOPE=1 # optional
    volumes:
      ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/calibre-web:/config
      # Where your preexisting calibre database is located.
      ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/calibre-web/books:/books
    # ports:
      # WebUI
      # - 8083:8083
    networks:
      default:
        aliases:
          - calibre-web
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true