# [Ardour](https://ardour.org/) is an open source, collaborative effort of a
# worldwide team including musicians, programmers, and professional recording
# engineers.

---

services:
  ardour:
    image: ghcr.io/linuxserver/ardour
    container_name: ardour
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - SUBFOLDER=/ # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/ardour${DOCKERCONFIGDIR:-}:/config
    # ports:
      # Ardour desktop gui 
      # - 3000:3000 # optional
      # Ardour desktop gui HTTPS 
      # - 3001:3001 # optional
    networks:
      default:
        aliases:
          - ardour
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}