# [Opera](https://www.opera.com/) is a multi-platform web browser developed by
# its namesake company Opera. The browser is based on Chromium, but
# distinguishes itself from other Chromium-based browsers (Chrome, Edge, etc.)
# through its user interface and other features.

---

services:
  opera:
    image: ghcr.io/linuxserver/opera
    container_name: opera
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - OPERA_CLI=https://www.linuxserver.io/ # optional
    volumes:
      ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/opera:/config
    # ports:
      # Opera desktop gui.
      # - 3000:3000
      # HTTPS Opera desktop gui.
      # - 3001:3001
    networks:
      default:
        aliases:
          - opera
    shm_size: "1gb"
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true