# [Rdesktop](http://xrdp.org/) - Containers containing full desktop environments
# in many popular flavors for Alpine, Ubuntu, Arch, and Fedora accessible via
# RDP.

---

services:
  rdesktop:
    image: ghcr.io/linuxserver/rdesktop
    container_name: rdesktop
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/rdesktop:/config
      # Docker Socket on the system, if you want to use Docker in the container
      # - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/rdesktop:/config
    # ports:
      # RDP access port
      # - 3389:3389
    networks:
      default:
        aliases:
          - rdesktop
    devices:
      # Add this for GL support (Linux hosts only)
      # - /dev/dri:/dev/dri # optional
    # shm_size: "1gb" # optional
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}