
# [Remmina](https://remmina.org/) is a remote desktop client written in GTK,
# aiming to be useful for system administrators and travellers, who need to work
# with lots of remote computers in front of either large or tiny screens.
# Remmina supports multiple network protocols, in an integrated and consistent
# user interface. Currently RDP, VNC, SPICE, SSH and EXEC are supported.

---

services:
  remmina:
    image: ghcr.io/linuxserver/remmina
    container_name: remmina
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/remmina:/config
    # ports:
      # - 3000:3000 # Remmina desktop gui.
      # - 3001:3001 # Remmina desktop gui HTTPS.
    networks:
      default:
        aliases:
          - remmina
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true