# [Remmina](https://remmina.org/) is a remote desktop client written in GTK,
# aiming to be useful for system administrators and travellers, who need to work
# with lots of remote computers in front of either large or tiny screens.
# Remmina supports multiple network protocols, in an integrated and consistent
# user interface. Currently RDP, VNC, SPICE, SSH and EXEC are supported.

---

services:
  remmina:
    image: ghcr.io/linuxserver/remmina
    container_name: remmina
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/remmina${DOCKERCONFIGDIR:-}:/config
    # ports:
      # # Remmina desktop gui.
      # - 3000:3000
      # # Remmina desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - remmina
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: ${NETWORK_EXTERNAL:-false}
