# [Pidgin](https://pidgin.im/) is a chat program which lets you log into
# accounts on multiple chat networks simultaneously. This means that you can be
# chatting with friends on XMPP and sitting in an IRC channel at the same time.

---
version: "2.1"
services:
  pidgin:
    image: ghcr.io/linuxserver/pidgin
    container_name: pidgin
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Users home directory in the container, stores local files and settings
      - ${BASEDIR:-/volume1/docker}/pidgin/config:/config
    ports:
      # Pidgin desktop gui.
      - 3000:3000
      # Pidgin desktop gui HTTPS.
      - 3001:3001
    restart: unless-stopped
