# [GitQlient](https://github.com/francescmm/GitQlient) is a multi-platform Git
# client originally forked from QGit. Nowadays it goes beyond of just a fork and
# adds a lot of new functionality.

---

services:
  gitqlient:
    image: ghcr.io/linuxserver/gitqlient
    container_name: gitqlient
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/gitqlient${DOCKERCONFIGDIR:-}:/config
    # ports:
      # GitQlient desktop gui.
      # - 3000:3000
      # HTTPS GitQlient desktop gui.
      # - 3001:3001
    networks:
      default:
        aliases:
          - gitqlient
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
#    external: true
