# [PairDrop](https://github.com/schlagmichdoch/PairDrop) is a sublime
# alternative to AirDrop that works on all platforms. Send images, documents or
# text via peer to peer connection to devices in the same local network/Wi-Fi or
# to paired devices.

---

services:
  pairdrop:
    image: ghcr.io/linuxserver/pairdrop
    container_name: pairdrop
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - RATE_LIMIT=false # optional
      # - WS_FALLBACK=false # optional
      # - RTC_CONFIG= # optional
      # - DEBUG_MODE=false # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/pairdrop:/config
    # ports:
      # http gui
      # - 3000:3000
    networks:
      default:
        aliases:
          - pairdrop
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}