# [Monica](https://github.com/monicahq/monica) is an open source personal
# relationship management system, that lets you document your life.

---

services:
  monica:
    image: ghcr.io/linuxserver/monica
    container_name: monica
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - DB_HOST=
      - DB_PORT=
      - DB_USERNAME=
      - DB_PASSWORD=
      - DB_DATABASE=
      # - APP_URL=http://localhost:80 # optional
      # - TRUSTED_PROXIES= # optional
      # - APP_ENV=local # optional
      # - APP_DISABLE_SIGNUP=true # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/monica:/config
    # ports:
      # http gui
      # - 80:80
      # https gui
      # - 443:443
    networks:
      default:
        aliases:
          - monica
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true