
# [Airsonic-advanced](https://github.com/kagemomiji/airsonic-advanced) is a
# free, web-based media streamer, providing ubiquitious access to your music.
# Use it to share your music with friends, or to listen to your own music while
# at work. You can stream to multiple players simultaneously, for instance to
# one player in your kitchen and another in your living room.

---

services:
  airsonic-advanced:
    image: ghcr.io/linuxserver/airsonic-advanced
    container_name: airsonic-advanced
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - CONTEXT_PATH= # optional
      # - JAVA_OPTS= # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/airsonic-advanced:/config
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/airsonic-advanced/playlists:/playlists
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/airsonic-advanced/podcasts:/podcasts
      - ${DOCKERSTORAGEDIR:-/volume1/data}/media:/mnt/data/media
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/airsonic-advanced/media:/media
    # ports:
      # - 4040:4040 # WebUI
    networks:
      default:
        aliases:
          - airsonic-advanced
    devices:
      # Only needed to pass your host sound device to Airsonic's Java jukebox player.
      - /dev/snd:/dev/snd # optional
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true