# [RustDesk](https://rustdesk.com/) is a full-featured open source remote
# control alternative for self-hosting and security with minimal configuration.

---
version: "2.1"
services:
  rustdesk:
    image: ghcr.io/linuxserver/rustdesk
    container_name: rustdesk
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Users home directory in the container, stores local files and settings
      - ${BASEDIR:-/volume1/docker}/rustdesk/config:/config
    ports:
      # RustDesk desktop gui.
      - 3000:3000
      # HTTPS Rustdesk desktop gui.
      - 3001:3001
    restart: unless-stopped
