# [FIleZilla](https://filezilla-project.org/) Client is a fast and reliable
# cross-platform FTP, FTPS and SFTP client with lots of useful features and an
# intuitive graphical user interface.

---
version: "2.1"
services:
  filezilla:
    image: ghcr.io/linuxserver/filezilla
    container_name: filezilla
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Users home directory in the container, stores local files and settings
      - ${BASEDIR:-/volume1/docker}/filezilla/config:/config
    ports:
      # FileZilla desktop gui.
      - 3000:3000
      # FileZilla desktop gui HTTPS.
      - 3001:3001
    restart: unless-stopped
