
# [Transmission](https://www.transmissionbt.com/) is designed for easy, powerful
# use. Transmission has the features you want from a BitTorrent client:
# encryption, a web interface, peer exchange, magnet links, DHT, µTP, UPnP and
# NAT-PMP port forwarding, webseed support, watch directories, tracker editing,
# global and per-torrent speed limits, and more.

---

services:
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - TRANSMISSION_WEB_HOME= # optional
      # - USER= # optional
      # - PASS= # optional
      # - WHITELIST= # optional
      # - PEERPORT= # optional
      # - HOST_WHITELIST= # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/transmission:/config
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/transmission/watch:/watch
      - ${DOCKERSTORAGEDIR:-/volume1/data}/downloads:/mnt/data/downloads
    # ports:
      # - 9091:9091 # WebUI
      # - 51413:51413 # Torrent Port TCP
      # - 51413:51413/udp # Torrent Port UDP
    networks:
      default:
        aliases:
          - transmission
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true