# [Bookstack](https://github.com/BookStackApp/BookStack) is a free and open
# source Wiki designed for creating beautiful documentation. Featuring a simple,
# but powerful WYSIWYG editor it allows for teams to create detailed and useful
# documentation with ease. Powered by SQL and including a Markdown editor for
# those who prefer it, BookStack is geared towards making documentation more of
# a pleasure than a chore. For more information on BookStack visit their website
# and check it out: https://www.bookstackapp.com

---

services:
  bookstack:
    image: ghcr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - APP_URL=
      - APP_KEY=
      - DB_HOST=
      - DB_PORT=3306
      - DB_USERNAME=
      - DB_PASSWORD=
      - DB_DATABASE=
      # - QUEUE_CONNECTION= # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/bookstack:/config
    # ports:
      # http/s web interface.
      # - 6875:80
    networks:
      default:
        aliases:
          - bookstack
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true