# This internal tool is used as a desktop sandbox in our CI process to grab a
# screenshot of a hopefully functional endpoint

---

services:
  tester:
    image: ghcr.io/linuxserver/tester
    container_name: tester
    environment:
      - URL=http://google.com
    # volumes:
    # ports:
      # # WebUI
      # - 3000:3000
    networks:
      default:
        aliases:
          - tester
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
