
# This internal tool is used as a desktop sandbox in our CI process to grab a
# screenshot of a hopefully functional endpoint

---

services:
  tester:
    image: ghcr.io/linuxserver/tester
    container_name: tester
    environment:
      - URL=http://google.com
    # ports:
      # - 3000:3000 # WebUI
    networks:
      default:
        aliases:
          - tester
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true