
# [Healthchecks](https://github.com/healthchecks/healthchecks) is a watchdog for
# your cron jobs. It's a web server that listens for pings from your cron jobs,
# plus a web interface.

---

services:
  healthchecks:
    image: ghcr.io/linuxserver/healthchecks
    container_name: healthchecks
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - SITE_ROOT=
      - SITE_NAME=
      - SUPERUSER_EMAIL=
      - SUPERUSER_PASSWORD=
      # - ALLOWED_HOSTS= # optional
      # - APPRISE_ENABLED=False # optional
      # - CSRF_TRUSTED_ORIGINS= # optional
      # - DEBUG=True # optional
      # - DEFAULT_FROM_EMAIL= # optional
      # - EMAIL_HOST= # optional
      # - EMAIL_PORT= # optional
      # - EMAIL_HOST_USER= # optional
      # - EMAIL_HOST_PASSWORD= # optional
      # - EMAIL_USE_TLS= # optional
      # - INTEGRATIONS_ALLOW_PRIVATE_IPS= # optional
      # - PING_EMAIL_DOMAIN= # optional
      # - RP_ID= # optional
      # - SECRET_KEY= # optional
      # - SITE_LOGO_URL= # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/healthchecks:/config
    # ports:
      # - 8000:8000 # Healthchecks Web UI
      # - 2525:2525 # Port for inbound SMTP pings # optional
    networks:
      default:
        aliases:
          - healthchecks
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true