# [Kasm](https://www.kasmweb.com/?utm_campaign=LinuxServer&utm_source=listing)
# Workspaces is a docker container streaming platform for delivering browser-
# based access to desktops, applications, and web services. Kasm uses devops-
# enabled Containerized Desktop Infrastructure (CDI) to create on-demand,
# disposable, docker containers that are accessible via web browser. Example
# use-cases include Remote Browser Isolation (RBI), Data Loss Prevention (DLP),
# Desktop as a Service (DaaS), Secure Remote Access Services (RAS), and Open
# Source Intelligence (OSINT) collections. The rendering of the graphical-based
# containers is powered by the open-source project
# [KasmVNC](https://www.kasmweb.com/kasmvnc.html?utm_campaign=LinuxServer&utm_source=kasmvnc).

---

services:
  kasm:
    image: ghcr.io/linuxserver/kasm
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=443
      # - DOCKER_HUB_USERNAME=USER # optional
      # - DOCKER_HUB_PASSWORD=PASS # optional
      # - DOCKER_MTU=1500 # optional
    volumes:
      # Docker and installation storage.
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/kasm/opt:/opt
      # Optionally specify a path for persistent profile storage.
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/kasm/profiles:/profiles
      # Optional for gamepad support.
      # - /dev/input:/dev/input
      # Optional for gamepad support.
      # - /run/udev/data:/run/udev/data
    # ports:
      # Kasm Installation wizard. (https)
      # - 3000:3000
      # Kasm Workspaces interface. (https)
      # - 443:443
    networks:
      default:
        aliases:
          - kasm
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}