# [RustDesk](https://rustdesk.com/) is a full-featured open source remote
# control alternative for self-hosting and security with minimal configuration.

---

services:
  rustdesk:
    image: ghcr.io/linuxserver/rustdesk
    container_name: rustdesk
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/rustdesk${DOCKERCONFIGDIR:-}:/config
    # ports:
      # RustDesk desktop gui.
      # - 3000:3000
      # HTTPS Rustdesk desktop gui.
      # - 3001:3001
    networks:
      default:
        aliases:
          - rustdesk
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}