
# [RustDesk](https://rustdesk.com/) is a full-featured open source remote
# control alternative for self-hosting and security with minimal configuration.

---

services:
  rustdesk:
    image: ghcr.io/linuxserver/rustdesk
    container_name: rustdesk
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/rustdesk:/config
    # ports:
      # - 3000:3000 # RustDesk desktop gui.
      # - 3001:3001 # HTTPS Rustdesk desktop gui.
    networks:
      default:
        aliases:
          - rustdesk
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true