# [Jellyfin](https://github.com/jellyfin/jellyfin) is a Free Software Media
# System that puts you in control of managing and streaming your media. It is an
# alternative to the proprietary Emby and Plex, to provide media from a
# dedicated server to end-user devices via multiple apps. Jellyfin is descended
# from Emby's 3.5.2 release and ported to the .NET Core framework to enable full
# cross-platform support. There are no strings attached, no premium licenses or
# features, and no hidden agendas: just a team who want to build something
# better and work together to achieve it.

---

services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - JELLYFIN_PublishedServerUrl=http://192.168.0.5 # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/jellyfin${DOCKERCONFIGDIR:-}:/config
      - ${DOCKERSTORAGEPATH:-/volume1/data}/media:${DOCKERMOUNTPATH:-/mnt/data}/media
    # ports:
      # Http webUI.
      # - 8096:8096
      # Optional - Https webUI (you need to set up your own certificate). 
      # - 8920:8920 # optional
      # Optional - Allows clients to discover Jellyfin on the local network. 
      # - 7359:7359/udp # optional
      # Optional - Service discovery used by DNLA and clients. 
      # - 1900:1900/udp # optional
    networks:
      default:
        aliases:
          - jellyfin
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}