# [Yaak](https://yaak.app/) is a desktop API client for organizing and executing
# REST, GraphQL, and gRPC requests. It's built using
# [Tauri](https://tauri.app/), [Rust](https://www.rust-lang.org/), and
# [ReactJS](https://react.dev/).

---
version: "2.1"
services:
  yaak:
    image: ghcr.io/linuxserver/yaak
    container_name: yaak
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # specify a timezone to use, see this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Where yaak should store its config and data.
      - ${BASEDIR:-/volume1/docker}/yaak/config:/config
    ports:
      # Yaak desktop gui.
      - 3000:3000
      # Yaak desktop gui HTTPS.
      - 3001:3001
    restart: unless-stopped
