# [Yaak](https://yaak.app/) is a desktop API client for organizing and executing
# REST, GraphQL, and gRPC requests. It's built using
# [Tauri](https://tauri.app/), [Rust](https://www.rust-lang.org/), and
# [ReactJS](https://react.dev/).

---

services:
  yaak:
    image: ghcr.io/linuxserver/yaak
    container_name: yaak
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/yaak${DOCKERCONFIGDIR:-}:/config
    # ports:
      # # Yaak desktop gui.
      # - 3000:3000
      # # Yaak desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - yaak
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
