# [Blender](https://www.blender.org/) is a free and open-source 3D computer
# graphics software toolset used for creating animated films, visual effects,
# art, 3D printed models, motion graphics, interactive 3D applications, virtual
# reality, and computer games. **This image does not support GPU rendering out
# of the box only accelerated workspace experience**

---

services:
  blender:
    image: ghcr.io/linuxserver/blender
    container_name: blender
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - SUBFOLDER=/ # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/blender${DOCKERCONFIGDIR:-}:/config
    # ports:
      # # Blender desktop gui
      # - 3000:3000
      # # Blender desktop gui HTTPS
      # - 3001:3001
    networks:
      default:
        aliases:
          - blender
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
