
# [Firefox](https://www.mozilla.org/en-US/firefox/) Browser, also known as
# Mozilla Firefox or simply Firefox, is a free and open-source web browser
# developed by the Mozilla Foundation and its subsidiary, the Mozilla
# Corporation. Firefox uses the Gecko layout engine to render web pages, which
# implements current and anticipated web standards.

---

services:
  firefox:
    image: ghcr.io/linuxserver/firefox
    container_name: firefox
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - FIREFOX_CLI=https://www.linuxserver.io/ # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/firefox:/config
    # ports:
      # - 3000:3000 # Firefox desktop gui.
      # - 3001:3001 # Firefox desktop gui HTTPS.
    networks:
      default:
        aliases:
          - firefox
    shm_size: "1gb"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true