
# [Bambu Studio](https://bambulab.com/en/download/studio) is an open-source,
# cutting-edge, feature-rich slicing software. It contains project-based
# workflows, systematically optimized slicing algorithms, and an easy-to-use
# graphical interface, bringing users an incredibly smooth printing experience.

---

services:
  bambustudio:
    image: ghcr.io/linuxserver/bambustudio
    container_name: bambustudio
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - DARK_MODE=true # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/bambustudio:/config
    # ports:
      # - 3000:3000 # Bambu Studio desktop gui.
      # - 3001:3001 # Bambu Studio desktop gui HTTPS.
    networks:
      default:
        aliases:
          - bambustudio
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true