
# [Duckdns](https://duckdns.org/) is a free service which will point a DNS (sub
# domains of duckdns.org) to an IP of your choice. The service is completely
# free, and doesn't require reactivation or forum posts to maintain its
# existence.

---

services:
  duckdns:
    image: ghcr.io/linuxserver/duckdns
    container_name: duckdns
    # network_mode: host # optional
    environment:
      # for UserID
      # - PUID=${PUID:-1024} # optional
      # for GroupID
      # - PGID=${PGID:-100} # optional
      # for UMASK
      # - UMASK=${UMASK:-002} # optional
      # for timezone
      # - TZ=${TZ:-America/Chicago} # optional
      - SUBDOMAINS=subdomain1,subdomain2
      - TOKEN=token
      # - UPDATE_IP=ipv4 # optional
      # - LOG_FILE=false # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/duckdns:/config
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/duckdns:/config
    ports:
      - 80:80 # Application WebUI
    networks:
      default:
        aliases:
          - duckdns
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true