# [Duckdns](https://duckdns.org/) is a free service which will point a DNS (sub
# domains of duckdns.org) to an IP of your choice. The service is completely
# free, and doesn't require reactivation or forum posts to maintain its
# existence.

---

services:
  duckdns:
    image: ghcr.io/linuxserver/duckdns
    container_name: duckdns
    # network_mode: host # optional
    environment:
      # # for UserID
      # - PUID=${PUID:-1024} # optional
      # # for GroupID
      # - PGID=${PGID:-100} # optional
      # # for UMASK
      # - UMASK=${UMASK:-002} # optional
      # # specify a timezone to use, see this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
      # - TZ=${TZ:-America/Chicago} # optional
      - SUBDOMAINS=subdomain1,subdomain2
      - TOKEN=token
      # - UPDATE_IP=ipv4 # optional
      # - LOG_FILE=false # optional
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/duckdns${DOCKERCONFIGDIR:-}:/config
    ports:
      # Application WebUI
      - 80:80
    networks:
      default:
        aliases:
          - duckdns
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: ${NETWORK_EXTERNAL:-false}
