
# The [Qbittorrent](https://www.qbittorrent.org/) project aims to provide an
# open-source software alternative to µTorrent. qBittorrent is based on the Qt
# toolkit and libtorrent-rasterbar library.

---

services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/qbittorrent:/config
      - ${DOCKERSTORAGEDIR:-/volume1/data}/downloads:/mnt/data/downloads
    # ports:
      # - 8080:8080 # WebUI
      # - 6881:6881 # tcp connection port
      # - 6881:6881/udp # udp connection port
    networks:
      default:
        aliases:
          - qbittorrent
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true