# [Calligra](https://calligra.org/) is an office and graphic art suite by KDE.
# It is available for desktop PCs, tablet computers, and smartphones. It
# contains applications for word processing, spreadsheets, presentation, vector
# graphics, and editing databases.

---

services:
  calligra:
    image: ghcr.io/linuxserver/calligra
    container_name: calligra
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/calligra:/config
    # ports:
      # Calligra desktop gui.
      # - 3000:3000
      # Calligra desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - calligra
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true