
# [Emulatorjs](https://github.com/linuxserver/emulatorjs) - In browser web based
# emulation portable to nearly any device for many retro consoles. A mix of
# emulators is used between Libretro and EmulatorJS.

---

services:
  emulatorjs:
    image: ghcr.io/linuxserver/emulatorjs
    container_name: emulatorjs
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      # - SUBFOLDER=/ # optional
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/emulatorjs:/config
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/emulatorjs/data:/data
    # ports:
      # - 3000:3000 # Rom/artwork management interface, used to generate/manage config files and download artwork
      # - 80:80 # Emulation frontend containing static web files used to browse and launch games
      # - 4001:4001 # IPFS peering port, if you want to participate in the P2P network to distribute frontend artwork please forward this to the Internet # optional
    networks:
      default:
        aliases:
          - emulatorjs
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true