# [Habridge](https://github.com/bwssytems/ha-bridge/) emulates Philips Hue API
# to other home automation gateways such as an Amazon Echo/Dot Gen 1 (gen 2 has
# issues discovering ha-bridge) or other systems that support Philips Hue. The
# Bridge handles basic commands such as 'On', 'Off' and 'brightness' commands of
# the hue protocol. This bridge can control most devices that have a distinct
# API.

---

services:
  habridge:
    image: ghcr.io/linuxserver/habridge
    container_name: habridge
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
      - SEC_KEY=
    volumes:
      ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/habridge:/config
    # ports:
      # WebUI
      # - 8080:8080
      # HABridge communication port.
      # - 50000:50000
    networks:
      default:
        aliases:
          - habridge
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true