# The [Qbittorrent](https://www.qbittorrent.org/) project aims to provide an
# open-source software alternative to µTorrent. qBittorrent is based on the Qt
# toolkit and libtorrent-rasterbar library.

---
version: "2.1"
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
      # for changing the port of the web UI, see below for explanation
      - WEBUI_PORT=8080
      # for changing the port of tcp/udp connection, see below for explanation
      - TORRENTING_PORT=6881
    volumes:
      # Contains all relevant configuration files.
      - ${BASEDIR:-/volume1/docker}/qbittorrent/config:/config
      # Location of downloads on disk.
      - ${BASEDIR:-/volume1/docker}/qbittorrent/downloads:/downloads # optional
    ports:
      # WebUI
      - 8080:8080
      # tcp connection port
      - 6881:6881
      # udp connection port
      - 6881:6881/udp
    restart: unless-stopped
