# [Davos](https://github.com/linuxserver/davos) is an FTP automation tool that
# periodically scans given host locations for new files. It can be configured
# for various purposes, including listening for specific files to appear in the
# host location, ready for it to download and then move, if required. It also
# supports completion notifications as well as downstream API calls, to further
# the workflow.

---

services:
  davos:
    image: ghcr.io/linuxserver/davos
    container_name: davos
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/davos${DOCKERCONFIGDIR:-}:/config
      # davos's file download location
      - ${DOCKERCONFIGPATH:-/volume1/docker/appdata}/davos/download:/download
    # ports:
      # # This is the default port that davos runs under
      # - 8080:8080
    networks:
      default:
        aliases:
          - davos
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
