# [UltiMaker Cura](https://ultimaker.com/software/ultimaker-cura/) is free,
# easy-to-use 3D printing software trusted by millions of users. Fine-tune your
# 3D model with 400+ settings for the best slicing and printing results.

---

services:
  cura:
    image: ghcr.io/linuxserver/cura
    container_name: cura
    environment:
      - PUID=${PUID:-1024}
      - PGID=${PGID:-100}
      - UMASK=${UMASK:-002}
      - TZ=${TZ:-America/Chicago}
    volumes:
      - ${DOCKERCONFIGDIR:-/volume1/docker/appdata}/cura:/config
    # ports:
      # Cura desktop gui.
      # - 3000:3000
      # Cura desktop gui HTTPS.
      # - 3001:3001
    networks:
      default:
        aliases:
          - cura
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK_NAME:-synobridge}
    external: true