# [Snapdrop](https://github.com/snapdrop/snapdrop) A local file sharing in your
# browser. Inspired by Apple's Airdrop.

---
version: "2.1"
services:
  snapdrop:
    image: ghcr.io/linuxserver/snapdrop
    container_name: snapdrop
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Persistent config files
      - ${BASEDIR:-/volume1/docker}/snapdrop/config:/config
    ports:
      # http gui
      - 80:80
      # https gui
      - 443:443
    restart: unless-stopped
