# [Shotcut](https://www.shotcut.org/) is a free, open source, cross-platform
# video editor.

---
version: "2.1"
services:
  shotcut:
    image: ghcr.io/linuxserver/shotcut
    container_name: shotcut
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # for UMASK
      - UMASK=${UMASK:-002}
      # for timezone
      - TZ=${TZ:-America/Chicago}
    volumes:
      # Where Shotcut should store its config.
      - ${BASEDIR:-/volume1/docker}/shotcut/config:/config
    ports:
      # Shotcut desktop gui.
      - 3000:3000
      # Shotcut desktop gui HTTPS.
      - 3001:3001
    restart: unless-stopped
